### ISSUE TITLE
Styling issue in subscriptions.

### ISSUE THREAD

**Issue by letsintegreat** [OWASP/BLT#1005]
The perks of subscriptions do not have a consistent style (Refer the image below).

![image](https://user-images.githubusercontent.com/37345795/209430686-2bcd7d71-b275-443a-bc45-c90b54786489.png)

**Comment by ManishBisht777** [comment]
i want to work on this

**Comment by fredfalcon** [comment]
You can type /assign

**Comment by ManishBisht777** [comment]
it looks good to me though but if we did try to fix the height it looks like this
![image](https://user-images.githubusercontent.com/89926834/210391737-655de722-8cbb-40e9-b7af-18ee32cc95ee.png)
