### ISSUE TITLE
Create an API for current statistics

### ISSUE THREAD

**Issue by letsintegreat** [OWASP/BLT#1007]
We have added a current statistics section in the mobile app. Please create an API for these numbers - 

- Bugs
- Users
- Hunts
- Domains

![image](https://user-images.githubusercontent.com/37345795/209585370-6b79011b-8af9-4ab4-8987-6052ab44c019.png)

**Comment by roopeshsn** [comment]
Hi, @letsintegreat! I would like to work on this issue.

**Comment by fredfalcon** [comment]
You can type /assign
