### ISSUE TITLE
Footer is not like figma file 

### ISSUE THREAD

**Issue by ConnectBhawna** [OWASP/BLT#1009]
![Screenshot from 2023-01-02 16-08-55](https://user-images.githubusercontent.com/81790585/210220698-50108f49-38bb-4372-b57e-8ddfeaf0f023.png)

**Comment by AtmegaBuzz** [comment]
Hey @Bhawna1203 
1. we need footer like this 
![image](https://user-images.githubusercontent.com/68425016/213904092-f6d39c34-6fed-4ce5-9bbd-c0c7f25638ec.png)
and add the language change dropdown where ever you feel it will look good, also make footer responsive.
2. remove this floating thing in bottom left corner 
![image](https://user-images.githubusercontent.com/68425016/213904104-244995fa-5b7f-4709-b17c-386750a92140.png)

**Comment by fredfalcon** [comment]
For the language select we can have a flag drop down

**Comment by Bhawna1203** [comment]
Okk @AtmegaBuzz @fredfalcon will make the changes

**Comment by Frs2304** [comment]
I can't see the footer image in img/white_logo.png
what should I do?

**Comment by co-decode** [comment]
I'd like to have a look at this.

**Comment by fredfalcon** [comment]
The footer is mostly done - we mainly need the steemit icon turned white and the language select styled.
