### ISSUE TITLE
Login Signup button alignment in small devices 

### ISSUE THREAD

**Issue by Vineetttt** [OWASP/BLT#1046]
![buggggggggggggggggg](https://user-images.githubusercontent.com/105866260/216821011-50e91a76-da81-459c-8a0d-faddb9c7f311.png)
The login and signup buttons are covering up the navbar content for mobile devices.

**Comment by AtmegaBuzz** [comment]
Hey @Vineetttt can you tell me the screen width you used in this issue. I think we've tested it for most of the mobile's and it didn't break

**Comment by Vineetttt** [comment]
It's for 300 pixels and below

**Comment by AtmegaBuzz** [comment]
I think that is not a major issue cause most of mobiles have 350px+ screen width width. still if you want to work on it you can other wise you can close it.

**Comment by Vineetttt** [comment]
Okay great

**Comment by Vineetttt** [comment]
Okay great
