### ISSUE TITLE
Make sure all templates are using the new dynamic variables 

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#1073]
For 
PROJECT_NAME
DOMAIN_NAME
FQDN
There are about 38 templates to replace the word “bugheist” in with these new variables

**Comment by Kej-r03** [comment]
Please assign this to me. I can work on this issue

**Comment by AtmegaBuzz** [comment]
you can self assign using /assign

**Comment by Kej-r03** [comment]
@fredfalcon my bad, I overlooked some of the files. Hopefully this PR resolves the issue
