### ISSUE TITLE
Update GitHub post code to work with multiple screenshots 

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#1075]
![EA70146B-1262-43A8-8EC3-BB27D7E660D3](https://user-images.githubusercontent.com/7475382/220067918-33e9e631-c184-42e9-a474-4950c267afec.png)

move it below the screenshots processing loop and append each file to the issue json

**Comment by Kej-r03** [comment]
HI @fredfalcon, I was working around with this issue and I would like to share a few concerns
1. Each obj, being an instance of `Issue` model, can have only one screenshot file appended to it, (also in the html template, there is only one file input), so `request.FILES.getlist("screenshots")` returns only 1 file, so I dont think there is any need for us to iterate over the loop you have mentioned
2. Also, I still attempted to put it inside that loop, but I found that each element of the `request.FILES.getlist("screenshots")` is of type `InMemoryUploadedFile` Django model, which has no attribute to extract url of the file, which will be needed for the `obj.screenshot.url` (the highlighted part in the pic) part of the issue json.

Please suggest what is to be done next

**Comment by Kej-r03** [comment]
@fredfalcon Thanks, I went through the PR and understood what you were referring to. But I rather encountered an error while I was testing your code in the changed line 691 of your PR. I have attached the image of that error.
![photo_2023-02-22_11-22-03](https://user-images.githubusercontent.com/99071926/220534996-a0c6380c-1279-48ec-8e6c-5e337b0f023a.jpg)
I have taken an alternative approach in my PR, please take a look if that solves the issue
