### ISSUE TITLE
Bug:  invalid link on automated Issue generated by bugheist  

### ISSUE THREAD

**Issue by AtmegaBuzz** [OWASP/BLT#1094]
**Describe the bug**

# Bug reported on Bugheist
![image](https://user-images.githubusercontent.com/68425016/222183521-b1fd9749-e9ec-44d5-97f6-85bf3b015b6f.png)

# Automated Issue generated by bugheist
![image](https://user-images.githubusercontent.com/68425016/222183426-1bf1bb7d-2d5a-4651-8531-8f6d5d69a31d.png)

issue id is different in generated link 

**To Reproduce**
1. Go to 'bugheist.com'
2. report a bug
3. now see the github issue
4. compare both id's, both will be different and the link will give not found response

**Comment by JisanAR03** [comment]
@DonnieBLT  This doesn't exist anymore. because when user create an issue, it doesn't redirect to issue page.
