### ISSUE TITLE
upvote and downvote on issues (show like counts, and add a dislike and show counts) (different than flag)

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#1101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by letsintegreat** [comment]
> do we already have this?

Yes, I believe "like" and "flag" on the issue page is equivalent to "upvote" and "downvote" respectively.

**Comment by DonnieBLT** [comment]
dislike would be different than flag - so for this we can have like and dislike next to each other and add the dislike functionality.
