### ISSUE TITLE
When an issue is hidden, make sure that it's corresponding image in the BLT hosted files is also hidden and not public

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#1104]

**Comment by pranav-iitr** [comment]
@fredfalcon is there any specific page where image should not come? or in the sites url acss should be blocked for the Image

**Comment by pranav-iitr** [comment]
So whenever there is an api call to blt it should only return the google cloud image CDN url if issue is not hidden?

**Comment by pranav-iitr** [comment]
Thank you for the clarification

**Comment by pranav-iitr** [comment]
possible approach could be on changing to hidden change image name in the GCP and we only render the new image in-front of concerned parties only?
