### ISSUE TITLE
Setup Media Relations

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#111]

**Comment by souravbadami** [comment]
Hi @seanauriti -- Could you please update the description about the issue on what has to be done ? Thanks!

**Comment by seanauriti** [comment]
This is for @tarachris - I think it was done, we contacted 6 media outlets, did not hear back from them so maybe we can take a different approach.  Thank you.

**Comment by tarachris** [comment]
Many thanks, Sean.  If I could think about this & get back to you that
would be great......best, tara

Tara C. Williams
P: 973-783-7644
C: 973-986-9959
Tarachriswilliams@gmail.com

**Comment by seanauriti** [comment]
There is a blog now - https://steemit.com/@bugheist
