### ISSUE TITLE
issue when liking an issue

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#1131]
![image](https://user-images.githubusercontent.com/7475382/224851890-08328587-3047-425e-a18f-00041a98860c.png)

**Comment by AtmegaBuzz** [comment]
Is it happening in mobile app? seems to be working on website

**Comment by AtmegaBuzz** [comment]
@fredfalcon  error is due to no comma 
![image](https://user-images.githubusercontent.com/68425016/225083348-e8568509-aed9-4631-8b26-1277e57efc9b.png)

so the statement is evaluating to settings.EMAIL_TO_STRING[liked_user.email] and that's why getting index cannot be string

**Comment by AtmegaBuzz** [comment]
its solved 
![image](https://user-images.githubusercontent.com/68425016/225961108-14cd07fb-747b-42a6-879e-eff2ca697f05.png)
