### ISSUE TITLE
make sure the BLT logo is showing as a default for a new project build - include the logo in the files and switch them based on the PROJECT_NAME variable or something that we have already

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#1133]

**Comment by Yashsomalkar** [comment]
@fredfalcon @AtmegaBuzz what does this line means: "switch the files on the basis of project name"

**Comment by AtmegaBuzz** [comment]
@Yashsomalkar this was fixed in my latest pr. forgot to link it

**Comment by AtmegaBuzz** [comment]
@fredfalcon we can close this

**Comment by Yashsomalkar** [comment]
> @Yashsomalkar this was fixed in my latest pr. forgot to link it 

Ah cool ok

**Comment by ATHARVA-GAWAS** [comment]
how can i contribute to this issue?? is this issue solved??
