### ISSUE TITLE
Setup codespaces for all BLT repos

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#1164]

**Comment by AtmegaBuzz** [comment]
@fredfalcon can you elaborate on what will be the expected result.
cause according to what i know is anyone can setup the codespace by  creating a codespace and selecting blt repo  
![image](https://user-images.githubusercontent.com/68425016/226090364-95c9b45f-7f70-457f-9f29-b38f2857c5cc.png)

**Comment by AtmegaBuzz** [comment]
@fredfalcon can be closed
