### ISSUE TITLE
add a bch address to the user profile - show it on their profile page to receive tips

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#1174]

**Comment by vigasinii** [comment]
I would like to work on this issue

**Comment by AtmegaBuzz** [comment]
@vigasinii Sure you can work on this, there is a file called contributors.json in the project https://github.com/OWASP/BLT/blob/main/contributors.json just add all the contributors info from the contributors section on the github https://github.com/OWASP/BLT/graphs/contributors. 
add id, name, location: Anyon and img : github image link rest make them as empty string

**Comment by professorabhay** [comment]
Hey @vigasinii, Are you still on it ?? 
If not then let me know.

**Comment by professorabhay** [comment]
Hey @AtmegaBuzz, Its been so long after assigning that issue to @vigasinii. 
I would like to work on it and resolve it in the timeline of 3-4 days. 
Assign it to me if you can !! 🙂

**Comment by AtmegaBuzz** [comment]
@professorabhay you can type / assign to assign it to yourself

**Comment by daemon-reconfig** [comment]
is this issue closed?
