### ISSUE TITLE
update contributor file to have 5 across

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#1179]
![image](https://user-images.githubusercontent.com/7475382/226139089-25230cec-bb95-40f3-84e0-9eaf1b922a11.png)

**Comment by shaomaiguanguan** [comment]
Hi I'd like to fix this. 
Just want to understand the requirement clearly: what does "5 across" mean in the requirement? Do you want 5 profiles in a row?
Thanks for the clarification:)

**Comment by shaomaiguanguan** [comment]
Thanks, I will prepare a PR soon
