### ISSUE TITLE
Add celery to the project

### ISSUE THREAD

**Issue by solo-daemon** [OWASP/BLT#1209]
@fredfalcon 

I was working on the **trademark search** and realised if we want to schedule trademark search jobs we will need a task queuer like celery in our project also this can be used for other features like sending **invite links** to users.

**Comment by solo-daemon** [comment]
@fredfalcon Sure we can go with that. I was reading about heroku scheduler and we need to manually schedule task which repeat after a particular interval. So that suits our job here. Still why I proposed celery was because it will help us to programmatically queue task so if a process takes more time( like sending request to update bacons in the contract ) it will not be included in the time request rather it will be queued. Even for sending emails we will not have to wait for the email to be sent we can return the response after some basic checks and then the process of sending email. 

Another example can be starting a bug hunt so let's say we want to send bug-hunters an email regarding a bug-hunt when it is started. I might be wrong but what I have understood we cannot do that with heroku scheduler. 

Though the cost for server will increase.

**Comment by DonnieBLT** [comment]
After further thought, we don't need a task queue as this will be a daily process that runs independently of the the user's interactions.
