### ISSUE TITLE
Project: Invites & Referrals

### ISSUE THREAD

**Issue by solo-daemon** [OWASP/BLT#1210]
UPDATE (2024/1/27): Have it be a template that will be sent by the user - lets do that to avoid any potential misuse - we can have a link in the email that will give the user a reward when the friend signs up.

- [ ] #581

**Comment by solo-daemon** [comment]
This can be achieved after #1209

**Comment by letsintegreat** [comment]
I don't think we should send the invites via our server. Even with API rate limiting, one can use a set of proxies to target email spam through us. Instead, we can draft an invite message with link and send an intent to user's email and messaging clients. Another plus is that - this way, the receiver will receive the invite via a trusted source, then the receiver is more likely to accept the invite.

**Comment by AtmegaBuzz** [comment]
I think it's ok to use email for sending invite from server. We were thinking of integrating invite friend with gmail, The main idea is that we create a token and send it in email to register and if registered with that email then the sender will automatically will be rewarded with BACON coins and this Invite api will be used in mobile app also. 
And schedulers aren't required for sending emails, we can use multi threading to achieve background tasks and thread will closed after email send or fail.

**Comment by DonnieBLT** [comment]
I like the idea of having it be a template that will be sent by the user - lets do that to avoid any potential misuse - we can have a link in the email that will give the user a reward when the friend signs up.

**Comment by kr-2003** [comment]
> I like the idea of having it be a template that will be sent by the user - lets do that to avoid any potential misuse - we can have a link in the email that will give the user a reward when the friend signs up.

@DonnieBLT In what form, does the user gets rewarded??
