### ISSUE TITLE
New Report a bug page

### ISSUE THREAD

**Issue by AtmegaBuzz** [OWASP/BLT#1231]
- UI Revamp 
- Allow For anonymous Bug-Reports
- Report Privately
We have identified several limitations in our current "Report a Bug" page that we believe could be improved upon.
Firstly, our current page does not provide users with a convenient way to describe their bug using markdown files or images within the text. This can result in a less than ideal bug report, potentially leading to delays in resolving the issue.
Additionally, we acknowledge that some users may prefer to report their bugs anonymously in order to protect their identity. Our current page does not offer this option. 

Furthermore, we do not currently have a "Report Privately" feature, which would allow users to report a bug that would only be seen by our company until it is fixed, at which point it could be made public.
To address these issues, I propose a redesign of our "Report a Bug" page that will include a user-friendly interface, improved accessibility, and support for markdown files and images. I will also incorporate the ability to report bugs anonymously and privately, which will increase user trust in our platform.
![image](https://user-images.githubusercontent.com/68425016/236639886-43c37ccd-3339-45ec-9efc-20920854f62d.png)

**Comment by DonnieBLT** [comment]
- [ ] add new report a bug page screenshot or design to figma so @DonnieBLT can give feedback
