### ISSUE TITLE
Add API Rate Limiter using django rest framework throttling 

### ISSUE THREAD

**Issue by AtmegaBuzz** [OWASP/BLT#1234]
To protect our backend from abuse, integrating an API rate limiter is an essential part. This will help in limiting the API calls per user. Thus protecting the Backend from bot’s and scripts trying to access BLT data.
Best tool which fits the case is Django-Rest-Frameworks API Throttling 
Image and code given below gives a better understanding of how Django REST API Throttling works. 

![image](https://user-images.githubusercontent.com/68425016/236640069-59553820-a07d-4537-8c4e-247a517fe8f1.png)

**Comment by AtmegaBuzz** [comment]
Done with API throtelling  
![image](https://github.com/OWASP/BLT/assets/68425016/58ee4f45-ab1f-46c5-be6c-d39621b1a9b1)

@just-ary27 @DonnieBLT  just wanted to know how many request an anyon and authenticated user can send ?
![image](https://github.com/OWASP/BLT/assets/68425016/499eeefd-29ad-42e1-a880-2ff9f14741af)

**Comment by just-ary27** [comment]
What endpoint are we talking about?
