### ISSUE TITLE
Solidity Smart Contract for Reward system integrated with backend and deployed on Bacon

### ISSUE THREAD

**Issue by AtmegaBuzz** [OWASP/BLT#1236]
To Implement a full-fledged reward system we need to deploy a smart contract which is capable of handling all the distribution logic of the BACON coin over our BACON chain; this contract will be triggered from our BLT backend when a user meets the reward criteria. 
I propose to create a smart contract using Solidity, which will facilitate the distribution of BACON Coins to bug hunters based on the severity of the bugs they discover. The smart contract will also enable the exchange of BACON Coins for merchandise and discounts in our premium programs. I will deploy this smart contract on our independent blockchain using Geth and the Proof of Authority (PoA) consensus algorithm.

![image](https://user-images.githubusercontent.com/68425016/236640184-dc32d6e6-615f-4259-9464-1d69ecf38be8.png)

**Comment by AtmegaBuzz** [comment]
# Running Nodes

![Image](https://github.com/OWASP/BLT/assets/68425016/3a83a10d-2a9e-417b-9345-7621297b24be)

# Bacon Tokens over Bacon chain 

![Image](https://github.com/OWASP/BLT/assets/68425016/432a35be-6a04-4f36-a979-3b70dd92408d)

# Deployed smart contract on Bacon chain 

![Image](https://github.com/OWASP/BLT/assets/68425016/7ef6ae30-af74-4403-868a-2123140d0e3b)

**Comment by ArpitKRS** [comment]
I have looked into this and request you to please assign this to me. /assign

**Comment by ArpitKRS** [comment]
Please explain where do I need to add my assigned solution code in the project file.

**Comment by DonnieBLT** [comment]
We decided to use our own blockchain to reduce costs and be independent of Ethereum see - Project: Bacon
