### ISSUE TITLE
Bug: Top hunts UI error message is not at center of screen for small screens

### ISSUE THREAD

**Issue by AtmegaBuzz** [OWASP/BLT#1267]
**Describe the bug**
The "No ongoing bughunts" error is not at center for small screens

**To Reproduce**
1. Go to BLT home page
2. make the screen width less than 526 px

**Expected behavior**
It should be at center of the page for every screen width

**Screenshots**
![image](https://github.com/OWASP/BLT/assets/68425016/adba021d-3569-4449-9bd5-6c9644183790)
![image](https://github.com/OWASP/BLT/assets/68425016/ac09ab2d-afd0-4e2b-afd4-344c94241d77)

**Comment by shubham-200315** [comment]
Can I Solve This Issue?

**Comment by West-Tiwan** [comment]
Please assign this task to me

**Comment by AtmegaBuzz** [comment]
@West-Tiwan @shubham-200315 You all can run the project and create your own issues if you see any breaking UI or problem as we didn't created issue for simple problems. Also join owasp BLT slack channel for further discussion and doubts  use this link to send yourselves an invite link https://owasp.org/slack/invite

**Comment by shubham-200315** [comment]
Hey @AtmegaBuzz there was breaking UI problem that you mentioned in issue and I have resolved it so should I create new issue for this and create PR for same or should I create PR for this issue only?

**Comment by AtmegaBuzz** [comment]
@shubham-200315  if you already resolved it then no need to create a issue just make a pr
