### ISSUE TITLE
Feature Request: New Issue page UI in tailwind

### ISSUE THREAD

**Issue by AtmegaBuzz** [OWASP/BLT#1268]
**Is your feature request related to a problem? Please describe.**
The current issue page is old and needs a new design update 
Issue Page: https://www.bugheist.com/issue/2121/ 

**Describe the solution you'd like**
Create a new issue page using tailwind you can take reference from https://flowbite.com/blocks/publisher/blog-templates/ as the view issue page has similar display flow as of a blog page.

**Additional context**
Current View Issue Page Screenshots:
![image](https://github.com/OWASP/BLT/assets/68425016/78856e26-423b-4106-a6de-31520d265b3a)
![image](https://github.com/OWASP/BLT/assets/68425016/8ca88df4-62cb-4ef6-94b5-f6307df61fa7)

**Comment by harshsbhandari** [comment]
hello @AtmegaBuzz , I would like to work on this issue

**Comment by sambhavgupta0705** [comment]
Can I take this one?

**Comment by shlok-2003** [comment]
Hey there @AtmegaBuzz, can you attach the new figma file in this thread

**Comment by AtmegaBuzz** [comment]
https://www.figma.com/file/JE0QlQ95FVpk0wG9HyFw4D/BLT-Website?type=design&node-id=0-1&t=uZy8FVsb2ayJAzVF-0
This is the new figma dont edit other screens, I would say take inspiration from the company dashboard screens. As this issue require constant communication i would suggest join owasp slack channel

**Comment by daemon-reconfig** [comment]
can I work on the good first issues here?
