### ISSUE TITLE
Bug: Search page broken UI 

### ISSUE THREAD

**Issue by AtmegaBuzz** [OWASP/BLT#1269]
**Describe the bug**
current search result page is not up to the mark and needs quick UI update/fix

**To Reproduce**
1. Go to https://www.bugheist.com/search/?query=profile

**Expected behavior**
- Remove the space in search and list issue section 
- add margin in list issue section and footer
- if possible make the UI more attractive and clean

**Screenshots**
![image](https://github.com/OWASP/BLT/assets/68425016/de650752-f80e-474d-b4dc-29f78d234085)
![image](https://github.com/OWASP/BLT/assets/68425016/ca0f0285-4611-468c-b313-3b5933c44d99)

**Comment by ayushsachan123** [comment]
please assign this Issue to me

**Comment by harshsbhandari** [comment]
Hey @AtmegaBuzz, can you please assign this issue to me, I would like to work on it.

**Comment by AtmegaBuzz** [comment]
You can assign yourself by commenting /assign

**Comment by professorabhay** [comment]
Hey @AtmegaBuzz, Seems like no one working on that issue. So, I'm going to assign myself and resolve it asap.

**Comment by professorabhay** [comment]
Hey @AtmegaBuzz, Can you please help me with the `DIR` ?

**Comment by professorabhay** [comment]
Hey @AtmegaBuzz, I make some changes in the website and its looking much better now. 
![image](https://github.com/OWASP/BLT/assets/76243309/9fd626c5-83f7-4306-99b0-8ba6acf7cb70)
![image](https://github.com/OWASP/BLT/assets/76243309/b55971ae-e298-47ec-b93a-75ccd71cf35d)
Please take a look to these changes and let me your views !!

**Comment by AtmegaBuzz** [comment]
Looks great Thanks @professorabhay
