### ISSUE TITLE
change python version in pyproject.toml and regenerate lock file / requirements

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1286]
-----> Read Python version from poetry.lock
-----> ~3.11 is not valid, please specify an exact Python version (e.g. 3.8.1 or ==3.8.1) in your pyproject.toml (and thus poetry.lock)

**Comment by AtmegaBuzz** [comment]
@DonnieBLT we are using 3.11.2 its specified 
![image](https://github.com/OWASP/BLT/assets/68425016/5891a884-cdc7-4362-992a-ec8829bb7be2)

**Comment by DonnieBLT** [comment]
I believe it has to be updated here - https://github.com/OWASP/BLT/blob/6e6d4eb807cdc6c4905b9fb03762fbc3bfe845e8/poetry.lock#L2427  I'll try it from Github but we may need to generate the hashes again.

**Comment by DonnieBLT** [comment]
That did the trick, thanks for looking into it!
