### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Ayushpanditmoto** [OWASP/BLT#1289]
![Screenshot_1](https://github.com/OWASP/BLT/assets/31253617/67b62037-b029-4f08-8c4b-620758cc96cc)
![Screenshot_2](https://github.com/OWASP/BLT/assets/31253617/ae23df6e-2a81-40e2-8ce1-80c37ee83fe1)

I Just Clone The repo after that docker build and compose up steps i followed i am facing this error

**Comment by Ayushpanditmoto** [comment]
Can anyone provide me slack channel link i am not able to join 

![Screenshot_3](https://github.com/OWASP/BLT/assets/31253617/e1d61c60-f9eb-4c44-8014-e7a8dd8684ec)

**Comment by AtmegaBuzz** [comment]
For the error that you are getting, just run python manage.py migrate to create all the tables in db

**Comment by Ayushpanditmoto** [comment]
@AtmegaBuzz thank you 😁 now its working
