### ISSUE TITLE
Slider in Horizontal bar

### ISSUE THREAD

**Issue by Ayushpanditmoto** [OWASP/BLT#1291]
https://github.com/OWASP/BLT/assets/31253617/f23c4a77-6926-494b-bca3-d0cf02b3816e

I think this issues in UI i found in my case

**Comment by Ayushpanditmoto** [comment]
@AtmegaBuzz  Hello Bhaiya Can i Work on this issue

**Comment by AtmegaBuzz** [comment]
@Ayushpanditmoto sure, you can self assign any issue

**Comment by officialarmannqureshi** [comment]
Hi, I am Nazim. I would like to work on this issue. Can you assign it to me?

**Comment by AtmegaBuzz** [comment]
Hey @officialarmannqureshi Welcome to the project BLT. You can self assign yourself by commenting /assign

**Comment by officialarmannqureshi** [comment]
Okay, thanks

**Comment by officialarmannqureshi** [comment]
> /assign

I am still working on this!

**Comment by JisanAR03** [comment]
I think this issue in closed. so i would be better if someone close this issue
