### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by daemon-reconfig** [OWASP/BLT#1374]
![screenshot_2023-08-22_at_12 22 42_am](https://github.com/OWASP/BLT/assets/69844188/e1a9650f-e2cb-4b2d-be67-6c0d5d481c27)
found this bug while signing up into BLT.
I had filled out my details and after clicking on signing up this showed up.

**Comment by AtmegaBuzz** [comment]
I just tried to replicate it on my end but here its working fine, this sometimes happen when your form doesn't submit due to some network reasons and when you try submitting it again the csrf token doesn't match with backend
