### ISSUE TITLE
Bug: On hovering `Add Comment` is almost invisible

### ISSUE THREAD

**Issue by Prakhar-Shankar** [OWASP/BLT#1379]
**Describe the bug**

On hovering `Add Comment` is almost invisible

**To Reproduce**
1. Go to https://www.bugheist.com/issue/2129/
2. Scroll down to comment section
3. Hover to `Add Comment` button.
4. See the error

**Expected behavior**
On hovering the button should be visible 

**Screenshots**
Before hovering - 

![image](https://github.com/OWASP/BLT/assets/97254881/d91f985e-3660-4ed6-8b7c-9f64606f0666)

After hovering -

![image](https://github.com/OWASP/BLT/assets/97254881/302846e3-983d-4d02-b2a6-85fac7f158c7)

**Comment by officialarmannqureshi** [comment]
Assign it to me

**Comment by Prakhar-Shankar** [comment]
> Assign it to me

I am already working on it.
