### ISSUE TITLE
Create a /sponsor page and link the "Sponsor a Prize" button to it

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1386]
**Sponsor a Monthly Prize on BLT**

---

**How Does Sponsoring Work?**

Our bug tracking platform, BLT, stands tall due to the dedication and hard work of our community. One of the pillars that bolsters this enthusiasm is the monthly prizes for our top bug finders. When you sponsor these prizes, you don't just uplift the platform; you celebrate and empower the brilliant minds behind the bug findings.

---

**Donate to the Monthly Prize Pool**

Elevate the efforts of the BLT community by contributing to our monthly prize pool. Your donation directly rewards the top performers, fostering a culture of excellence.

---

```
+-----------------------------------------------+
|                                               |
|   **Bitcoin Cash (BCH) Donation Address**     |
|                                               |
|   `bitcoincash:qqeht8vnwag20yv8dvtcrd4ujx09fwxwsqqqw93w88`  |
|                                               |
+-----------------------------------------------+
```

---

**Process to Sponsor a Prize:**

1. **Choose Your Donation Amount:** Whether you want to give a modest token of appreciation or a substantial prize, all contributions make a difference.
 
2. **Send the Donation:** Utilize the provided BCH address above to transfer your chosen donation.

3. **Recognition & Confirmation:** Upon receipt, we will both confirm and give due recognition to your contribution on our leaderboard.

---

**Determining the Winner:**

1. **Monthly Assessment:** Bug finders continuously submit their findings throughout the month. Each discovery gets scored based on parameters like severity, rarity, and report accuracy.

2. **Leaderboard Dynamics:** At month-end, all participants are ranked on our leaderboard using their cumulative scores.

3. **Rewarding Excellence:** The top bug finder, leading the leaderboard, receives the entirety of the month's prize pool on the first day of the subsequent month.

---

**Transparent Operations & Genuine Trust:**

Every cent of your donation serves its intended purpose. We ensure full transparency by making all transaction records accessible to the community.

---

**Why Your Sponsorship Matters:**

1. **Enhancing Quality:** Monetary incentives drive bug finders to outdo their previous bests, leading to higher-quality findings.
  
2. **Community Engagement:** Regular contributions indicate a thriving BLT community that appreciates and values its members.

3. **Branding Opportunity:** As a sponsor, gain favorable visibility and goodwill among a dedicated community.

---

**Let’s Make a Difference Together!**

Your backing is instrumental in sculpting BLT's success. By choosing to contribute, you're endorsing quality, commitment, and collaborative growth. For any assistance or further information, please [contact our team].

Thank you for championing the spirit of excellence on BLT!

**Comment by thedudeontitan** [comment]
I would like to work on this

**Comment by thedudeontitan** [comment]
commit 2 in pull request #1387 solves this issue.
