### ISSUE TITLE
have comments

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#141]

**Comment by farziengineer** [comment]
Hello  @seanauriti. On which pages should we have the comments? I think this needs some discussion.
1. Can comments have sub-comments.
2. What effect will it have on the parent comment if the child comment is deleted. 

Thanks.

**Comment by souravbadami** [comment]
Hi @farziengineer -- I've created this new discussion channel for Bugheist. I think, it'll be better to discuss things there. Let me know your email address and I'll add you there. Also, @seanauriti -- If it's fine, I'll add you there too.

**Comment by seanauriti** [comment]
Sure, were on the OWASP Slack too #project-blt owasp.herokuapp.com

**Comment by souravbadami** [comment]
Ah, Thanks! @seanauriti
