### ISSUE TITLE
Feature Request: Replace Bootstrap with TailwindCSS for Navbar

### ISSUE THREAD

**Issue by thedudeontitan** [OWASP/BLT#1412]
**Is your feature request related to a problem? Please describe.**
The Navbar currently uses Bootstrap and Tailwind css partially, which is not ideal as the site is moving towards TailwindCSS.

**Describe the solution you'd like**
Replace Bootstrap with Tailwind CSS for navbar.

**Additional context**
N/A

**Comment by Rajrits** [comment]
please assign this task to me I would like to work on it.

**Comment by Rajrits** [comment]
Hello Sir @thedudeontitan , Please assign this task to me I would like to work on it.

**Comment by officialarmannqureshi** [comment]
Hi, @DonnieBLT  @AtmegaBuzz  Kindly assign this issue to me. I would like to work on it.
Thanks

**Comment by uraj323** [comment]
@AtmegaBuzz assign this to me please

**Comment by uraj323** [comment]
@AtmegaBuzz the nav bar is already is tailwaind css

**Comment by uraj323** [comment]
[navbar to tailwind](https://github.com/OWASP/BLT/pull/1477)

**Comment by uraj323** [comment]
#1478

**Comment by Atharva-Kanherkar** [comment]
Hi, is this issue fixed? If not, i would like to work on it! 
@DonnieBLT
