### ISSUE TITLE
 Get more points for submitting bugs on new web sites

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#146]

**Comment by Roboneet** [comment]
like , 5 points for a new website ?

**Comment by seanauriti** [comment]
Yes, it was added before and removed. This is more of a discussion point.
Do you think we should have this feature?

**Comment by Roboneet** [comment]
Yeah , it would naturally help in increasing the number of featured websites.

**Comment by seanauriti** [comment]
Ok, let's add it back, can probably just uncomment it. Thanks for your
feedback.
