### ISSUE TITLE
Bug: Contributors list still uses the old logo of twitter

### ISSUE THREAD

**Issue by Prakhar-Shankar** [OWASP/BLT#1471]
**Describe the bug**

Contributors list still uses the old logo of twitter

**To Reproduce**
1. Go to 'https://www.bugheist.com/'
2. Scroll down to 'footer'
3. Click on 'contributors'

**Expected behavior**
Update of logo of twitter should be there

**Screenshots**
![image](https://github.com/OWASP/BLT/assets/97254881/46b985f0-9fd4-4eab-baf9-6d9b9aa2b684)

**Comment by Hemanthhari2000** [comment]
Hi, I would like to contribute to this under Hacktoberfest. 
Can you please assign me this?

**Comment by Prakhar-Shankar** [comment]
> Hi, I would like to contribute to this under Hacktoberfest. Can you please assign me this?

Hi, I had already made a PR regarding this issue.

**Comment by manthan-sharma-23** [comment]
Hey Folks !
I have made a PR regarding this issue.

**Comment by DonnieBLT** [comment]
Thanks! Is it linked?

**Comment by manthan-sharma-23** [comment]
Yeah sorry i forgot to link.

**Comment by DonnieBLT** [comment]
There was a similar PR with the fontawesome x icon (updated version).  Can we use that method?

**Comment by manthan-sharma-23** [comment]
you are gonna use that PR only right  ?
or should i change my method?

**Comment by DonnieBLT** [comment]
It wasn't updated yet so you're welcome to get it in first. Unless I missed their update.

**Comment by manthan-sharma-23** [comment]
oh ok Thanks

**Comment by manthan-sharma-23** [comment]
@DonnieBLT  Hey I have changed the logo with fontawesome updated version. Please have a look. Thank you
