### ISSUE TITLE
Feature Request: Improve Local Setup documentation

### ISSUE THREAD

**Issue by CodeWithBishal** [OWASP/BLT#1479]
**Is your feature request related to a problem? Please describe.**
Improve documentation for `Development Server using Python Virtual Environment`. The documentation does not have any requirements.txt file which helps a new contributor to setup the project locally. I will also add a documentation for project setup using poetry.
Alternative virtualenv package: `virtualenv`

**Describe the solution you'd like**
I will add a requirements.txt file with the required packages which will help new contributors.

**Comment by DonnieBLT** [comment]
if you'd like to have the alternative setup using poetry install instead of requirements.txt that would be helpful
