### ISSUE TITLE
Bug: At - issue2 page ,, comment part "report" option is not needed

### ISSUE THREAD

**Issue by JisanAR03** [OWASP/BLT#1488]
**Describe the bug**
at URL: <main_url>/issue2/<post_id> ,, at comment part there is an option "report", which is not needed because on btl there is nothing depend on "report" and I confirm this one from @AtmegaBuzz  

**Screenshots**
![image](https://github.com/OWASP/BLT/assets/97744811/d9837659-fccc-4875-a8f0-6bc2bfc39f96)

**Comment by DonnieBLT** [comment]
This is to report or flag the comment, we require this functionality in case there is comment that goes against the terms.

**Comment by JisanAR03** [comment]
> This is to report or flag the comment, we require this functionality in case there is comment that goes against the terms.

that's for the review sir if possible please explain little bit more what your expectation ,i would love to implement.
