### ISSUE TITLE
Fix code scanning alert - Replacement of a substring with itself

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1513]
Tracking issue for:
- [ ] https://github.com/OWASP/BLT/security/code-scanning/80

![image](https://github.com/OWASP/BLT/assets/128622481/02aa1bea-1a1b-45e1-aef3-6c42a0228bcf)

**Comment by JisanAR03** [comment]
fixed #1522

**Comment by JisanAR03** [comment]
this error is fixed now

**Comment by DonnieBLT** [comment]
seems still open - 
![image](https://github.com/OWASP/BLT/assets/128622481/dcb75048-1e38-4444-8fb7-0d9c60c9978e)
