### ISSUE TITLE
Fix code scanning alert - Unsafe expansion of self-closing HTML tag

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1516]
Tracking issue for:
- [ ] https://github.com/OWASP/BLT/security/code-scanning/84

![image](https://github.com/OWASP/BLT/assets/128622481/d98de398-1fbd-4147-bc72-f5d1bb95a556)

@JisanAR03

**Comment by JisanAR03** [comment]
fixed with #1520

**Comment by manthan-sharma-23** [comment]
@JisanAR03  bro are you working on this ...?

**Comment by JisanAR03** [comment]
> @JisanAR03 bro are you working on this ...?

this is already fixed .. can you able to check after fixing the security issue?
