### ISSUE TITLE
user is not getting attached to issue when created without being logged in

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#152]

**Comment by souravbadami** [comment]
Hi @seanauriti -- I cannot reproduce this issue on latest master. Could you please update ?

**Comment by seanauriti** [comment]
It updates the activity stream but the issue itself is missing the user.
Happens on production.

**Comment by souravbadami** [comment]
Yes, I just went through the `Issue` model and the link between user and issue seems working.

**Comment by seanauriti** [comment]
It's a production only issue then. Or maybe only happens to me.

**Comment by seanauriti** [comment]
It still happens
