### ISSUE TITLE
Feature Request:  Adding a scroll to top button on home page 

### ISSUE THREAD

**Issue by Prakhar-Shankar** [OWASP/BLT#1547]
**Is your feature request related to a problem? Please describe.**
After scrolling down we have to scroll back to get at the top, every modern website have a feature of scrolling to top in one click.

**Describe the solution you'd like**
A button at the bottom right corner of the site which will help the user to scroll to the top.

**Comment by DonnieBLT** [comment]
We don't need this anymore with the current pagination - if / when we do continual scroll we can reopen this
