### ISSUE TITLE
SSL Error on accessing issue.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#158]
Accessing an issue causes an ssl error. Here's the screenshot of the stack trace.

![screenshot from 2017-05-28 07 15 47](https://cloud.githubusercontent.com/assets/11073943/26525490/5cb18362-4376-11e7-9d63-05fa088975d2.png)

**O/S**: Ubuntu 14.04

**Comment by seanauriti** [comment]
I think this is a local issue with your environment or an issue with the logo server.

**Comment by souravbadami** [comment]
@seanauriti -- I found a fix for this. It's due to `requests` package. Maybe, I'll open a PR for it ?

**Comment by seanauriti** [comment]
Ok yes, thanks.
