### ISSUE TITLE
Task: Implement effective infinite scroll on the new home page

### ISSUE THREAD

**Issue by errorassassin** [OWASP/BLT#1632]
Bugheist is adapting a new homepage with all the bugs listed on the homepage. Currently, all the bugs load without even scrolling.
The new home page is currently hosted at https://www.bugheist.com/newhome.

**Comment by sidling1** [comment]
Hey @errorassassin ,

The issue is that in views.py  , we gather all the bugs in one go from the database, but we want it to happen as the user scrolls forward in the home page ?

Is this what is to be implemented ?

**Comment by errorassassin** [comment]
> Hey @errorassassin ,
> 
> The issue is that in views.py  , we gather all the bugs in one go from the database, but we want it to happen as the user scrolls forward in the home page ?
> 
> Is this what is to be implemented ?

Yes, that would improve the user experience a lot.

**Comment by sidling1** [comment]
Can i work on this issue ?

**Comment by CodeWithBishal** [comment]
Sure, noone is working on this issue right now. Feel free to assign the issue to yourself using /assign.

P.S. also make sure the url changes after the pagination, e.g. after scroll when the page 2 is being loaded URL should contain "?page=2" hence it is easier to share a link to someone else with a specific page number.

@sidling1

**Comment by aakash2330** [comment]
please correct me if I'm wrong @CodeWithBishal  , we are here trying to remove the pagination bar and implement it by scrolling through the page instead ?

**Comment by CodeWithBishal** [comment]
@aakash2330 yes correct

**Comment by errorassassin** [comment]
just go to <base url>/newhome which would be localhost:8000/newhome by default

**Comment by HanilJain** [comment]
bugs in [newhome](http://localhost:8000/newhome/) which have are of different user and is_hidden=true they must be listed in the page or not.
https://github.com/OWASP/BLT/blob/80702b0c02e68aec123bc90685846c74118a75dd/website/views.py#L198C1-L199C1
here the bugs uses & operator which leads to list all but I think there must be an | operator there. am correct ?

**Comment by errorassassin** [comment]
> bugs in [newhome](http://localhost:8000/newhome/) which have are of different user and is_hidden=true they must be listed in the page or not. https://github.com/OWASP/BLT/blob/80702b0c02e68aec123bc90685846c74118a75dd/website/views.py#L198C1-L199C1 here the bugs uses & operator which leads to list all but I think there must be an | operator there. am I correct ?

No! Replacing the and with or would hide every Issue that's not mine as the second condition would be true whenever the Issue is not mine (mine means the user seeing the homepage). We want to hide all the Issues that are hidden **and** not mine.
Also, your way of creating an infinite scroll homepage is not effective as it loads all bugs on the first load of the website, even when the user is not scrolling down. We want to load the bugs as the user scrolls down, one page at a time.

**Comment by HanilJain** [comment]
thanks, got it. 
making the required changes.

**Comment by CodeWithBishal** [comment]
Hi @HanilJain,

If you have created a PR for this commit feel free to mention it with #<PR-ID>

**Comment by HanilJain** [comment]
fixed #1672

**Comment by HanilJain** [comment]
@errorassassin  Hi can you close this issue 
https://github.com/OWASP/BLT/pull/1672
PR is merged !

**Comment by errorassassin** [comment]
@HanilJain I dont think that was quite as expected, the page still loads all the bugs on the initial reload. Once again, what I had in my mind was something similar to twitter, loading content as the user scrolls down. Loading all the bugs initially has massively increased the loading time too.

**Comment by errorassassin** [comment]
observe the scrollbar on these social media websites like twitter

**Comment by HanilJain** [comment]
@errorassassin Hi thanks for informing.
it was small change in the code 
I have resolved in the https://github.com/OWASP/BLT/pull/1767

**Comment by HanilJain** [comment]
@errorassassin I think it seems correct to me now. as  new content can be seen loading and also the scroll bar.
are they any more change required?

**Comment by DonnieBLT** [comment]
Let's revert this please. I like the pagination better.
