### ISSUE TITLE
Bug: Broken UI in Report a bug page 

### ISSUE THREAD

**Issue by AtmegaBuzz** [OWASP/BLT#1683]
**Describe the bug**
I love this feature of directly selecting your domain but the design is not good. 
How about we put it in a box and  fix the alignment also make it scroll able horizontally. 

**To Reproduce**
https://www.bugheist.com/report/

**Expected behavior**
Make UI better and clean

**Screenshots**
![issue](https://github.com/OWASP/BLT/assets/68425016/4b9084cb-0032-4160-9b64-8b143e441c53)

**Additional context**
None

**Comment by DonnieBLT** [comment]
I think we can simply have the top 10 and fix the squares to not be squished. Maybe a nice bus but no scroll needed.
