### ISSUE TITLE
Bug: New Issue Details Page : footer

### ISSUE THREAD

**Issue by CodeWithBishal** [OWASP/BLT#1723]
Give a fixed height to the images in the footer

<img width="1440" alt="Screenshot 2024-01-29 at 1 56 54 PM" src="https://github.com/OWASP/BLT/assets/69814108/f08b6e74-9283-4bf9-b72b-189223f3c6af">

**Comment by ATHARVA-GAWAS** [comment]
@CodeWithBishal Hey please elaborate on this issue.

**Comment by CodeWithBishal** [comment]
Steps to reproduce: 

1) Visit the new homepage: https://www.bugheist.com/newhome/
2) Open the first issue e.g. https://www.bugheist.com/issue2/2182/
3) If you scroll to the bottom you will find "More Reports from"
4) Below you will find 4 issues with its images and the images dont have any specific dimensions hence looks bad in the layout

Possible Solution:
Give specific dimensions to the images

**Comment by ATHARVA-GAWAS** [comment]
thanks
