### ISSUE TITLE
Bug: TypeError at /api/v1/search/

### ISSUE THREAD

**Issue by HanilJain** [OWASP/BLT#1724]
**Describe the bug**
when type is changed to domain , User. It gives an error TypeError

**To Reproduce**
1. Go to 'base_url/api/v1/search/'
2. Click on 'type'
3. change down to 'domain/user'
4. search anything in it
5. See error

**Expected behavior**
should show the revelant data

**Screenshots**
![type error bug](https://github.com/OWASP/BLT/assets/119354421/e88fbf34-48f1-45ee-96f6-000588d47d9d)

**Comment by HanilJain** [comment]
@DonnieBLT could you please review

**Comment by DonnieBLT** [comment]
It looks like the issue that you attached is different from the one that was worked on

**Comment by HanilJain** [comment]
@DonnieBLT  I have added  commits for review. could you please check them. #1726

**Comment by DonnieBLT** [comment]
Is this issue happening in production?

**Comment by HanilJain** [comment]
yes it is !!

- https://blt.owasp.org/api/v1/search/?query=software&type=domain
- https://blt.owasp.org/api/v1/search/?query=admin&type=user
- neither options have label in it

![Screenshot 2024-02-09 095747](https://github.com/OWASP/BLT/assets/119354421/7e0b8896-7874-4595-94b9-70a85c30177e)
