### ISSUE TITLE
Bug: BLT Website not accessible

### ISSUE THREAD

**Issue by CodeWithBishal** [OWASP/BLT#1751]
**Describe the bug**
BLT Website is not accessible.

**To Reproduce**
Visit any pages of bugheist.com

**Screenshots**
<img width="1440" alt="Screenshot 2024-02-05 at 10 35 26 PM" src="https://github.com/OWASP/BLT/assets/69814108/c6a4c3f3-6476-47fa-9bdd-414b8fce3999">

**Comment by DonnieBLT** [comment]
It's now at blt.owasp.org

**Comment by CodeWithBishal** [comment]
Can we add 301 redirect from bugheist.com to blt.owasp.org?

**Comment by DonnieBLT** [comment]
Was thinking of setting up a new website maybe on render.com

**Comment by CodeWithBishal** [comment]
Alright!
Closing this issue
