### ISSUE TITLE
Design inconsistency with "Sponsor a Bug Hunt" button.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#176]
![screenshot from 2017-06-05 00 31 36](https://cloud.githubusercontent.com/assets/11073943/26764555/8f74c672-4986-11e7-94cd-69538e44824d.png)

The **Sponsor a Bug Hunt** button appears sandwiched between featured websites and activity block. It's difficult to identify it on the interface on a go. Maybe we can move it to the top navigation.

What's your opinion @seanauriti ?

**Comment by seanauriti** [comment]
Yes
