### ISSUE TITLE
Bug: no issues are working

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1779]
![image](https://github.com/OWASP/BLT/assets/128622481/9347a3b1-7fc6-4064-8aa6-0e1c5ebb5582)

**Comment by HanilJain** [comment]
\assign

**Comment by HanilJain** [comment]
@DonnieBLT could you please elaborate

**Comment by DonnieBLT** [comment]
Fixed here - https://github.com/OWASP/BLT/commit/496d6c4057bcd7469cc58279060f856c7e0f5124
