### ISSUE TITLE
Leaderboard v2 (Hackathon)

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1780]
We are thrilled to announce that this year, we've witnessed an extraordinary level of interest in the GSOC program, with a record number of students applying to participate. In line with our commitment to innovation and a transparent selection process, we're excited to introduce a new, dynamic approach to determining our next cohort.

**Introducing the Hackathon-Style Selection Process**

To ensure the selection process is as open and transparent as possible, we're adopting a hackathon-style method. This approach will not only allow applicants to showcase their talents but will also provide a fair platform for everyone to demonstrate their capabilities.

**How It Works**

- **Leaderboard Ranking:** similar to how we did the previous leaderboard issue where every contributor has a comment that they update we will do that for pull requests only. Starting from now until March 18, every new pull request made to any issue labeled task or project will earn you a point (projects are 2 points, tasks are 1 point), turning your contributions into potential opportunities to stand out in the selection process.
  
- **Top Contributors Take the Lead:** The effort and dedication you put into your contributions will be recognized. The top five contributors, as highlighted by our leaderboard, will be given higher priority in the final selection ranking. This means your hard work can significantly boost your chances of being selected for the GSOC program.

- **Final Announcement:** At the conclusion of the selection period, we will tally the points. The top five contributors will be announced and will receive priority consideration for their final proposals.

**Your Chance to Shine and Collaborate**

This is your new opportunity to demonstrate your skills and make a significant impact. The leaderboards are reset and everyone starts over now.  In the event that there is any discrepancy, we will take into consideration the first leaderboard, as well as any special circumstances. Dive into the issues, make meaningful contributions, and ascend the new leaderboard. We're looking for individuals who are passionate, innovative, and dedicated to excellence. Are you ready to rise to the challenge? 

**Need a Review? Ping Me on Slack!**

If you're working on a pull request and would like it reviewed, don't hesitate to ping me on Slack. I'm here to help and ensure your contributions are recognized as part of the selection process.

Let's make this year's selection process a showcase of the incredible talent and creativity within our applicant pool. We're eager to see the unique contributions you'll bring to the GSOC program.

Best of luck to all our participants!

**Comment by HanilJain** [comment]
@HanilJain 

-  Issues Closed

   https://github.com/OWASP/BLT/issues/1671     
   https://github.com/OWASP/BLT/issues/1717   
   https://github.com/OWASP/BLT/issues/1685    
   https://github.com/OWASP/BLT/issues/1724
   https://github.com/OWASP/BLT/issues/1632
   https://github.com/OWASP/BLT/issues/1777 
   https://github.com/OWASP/BLT/issues/1774



- Merged PRs

   https://github.com/OWASP/BLT/pull/1718
   https://github.com/OWASP/BLT/pull/1691
   https://github.com/OWASP/BLT/pull/1729
   https://github.com/OWASP/BLT/pull/1726
   https://github.com/OWASP/BLT/pull/1672
   https://github.com/OWASP/BLT/pull/1768
   https://github.com/OWASP/BLT/pull/1767
   https://github.com/OWASP/BLT/pull/1778
   https://github.com/OWASP/BLT/pull/1776

- Comments

   https://github.com/OWASP/BLT/pull/1691#issuecomment-1912021350
      [Many]

**Comment by DonnieBLT** [comment]
@HanilJain you can update the other leaderboard with these - this one is only for pull requests during the next few weeks.

**Comment by HanilJain** [comment]
> @HanilJain you can update the other leaderboard with these - this one is only for pull requests during the next few weeks.

PR which we made 2 days ago can be listed here ?
also is it merged PR ?

**Comment by HanilJain** [comment]
@HanilJain  

- ALL PR
 https://github.com/OWASP/BLT/pull/1776 
 https://github.com/OWASP/BLT/pull/1778

**Comment by JisanAR03** [comment]
@JisanAR03 

- All PR
    #1773

**Comment by ATHARVA-GAWAS** [comment]
[ATHARVA-GAWAS](https://github.com/ATHARVA-GAWAS)


PRs
https://github.com/OWASP/BLT/pull/1694
https://github.com/OWASP/BLT/pull/1747

**Comment by DonnieBLT** [comment]
Only PRs made from 2/15 - 3/16 are eligible for this leaderboard. As a note, we will also be taking into consideration the first leaderboard.

**Comment by Dante291** [comment]
@Dantelol291 

All PR

1. https://github.com/OWASP/BLT-Flutter/pull/349

**Comment by ayushsinha25** [comment]
@ayushsinha25

**Comment by ATHARVA-GAWAS** [comment]
@ATHARVA-GAWAS 

All PR:
1) https://github.com/OWASP/BLT/pull/1807
2) https://github.com/OWASP/BLT/pull/1809

**Comment by Sarthak5598** [comment]
@Sarthak5598 
All PR:
1.[Feature Request: Suggestions for BLT project #1816 #1817](https://github.com/OWASP/BLT/pull/1817)

**Comment by CodeWithBishal** [comment]
@CodeWithBishal 
All PR:

https://github.com/OWASP-BLT/BLT/pull/1956

**Comment by thedudeontitan** [comment]
@thedudeontitan 

All PRs:
- #1886 
- #1962 
- #1973
- #1985
- #1995
