### ISSUE TITLE
Bug: Logo Images not showing in compaines 

### ISSUE THREAD

**Issue by HanilJain** [OWASP/BLT#1789]
Due to different storage location in localhost and prod this bug occurs 
where prod stores in https://bhfiles.storage.googleapis.com/logos
localhost stores in https://blt.owasp.org/media//logos/victorinox.market.jpg (which does not work in prod)
![image](https://github.com/OWASP/BLT/assets/119354421/31cb168c-e3fc-4821-b52a-7e489349e7d3)

**Comment by DonnieBLT** [comment]
We use clearbit for the logos

**Comment by HanilJain** [comment]
> We use clearbit for the logos

<img src="{{MEDIA_URL}}{{MEIDA_ROOT}}/{{objects.logo}}" alt="{{objects.name}}">

if I use this for the logo it should work right ?

**Comment by DonnieBLT** [comment]
Take a look on how we do it on the issue page and company leaderboard
