### ISSUE TITLE
Task: When an issue is deleted from the database, make sure all related images in the bucket are also deleted

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1794]

**Comment by JisanAR03** [comment]
> This is not working with Google cloud storage. We will need to make sure it deletes from the bucket on Google Cloud

@DonnieBLT ,ok sure sir ,I will fix this one

**Comment by JisanAR03** [comment]
![image](https://github.com/OWASP-BLT/BLT/assets/97744811/cd245971-bd3d-4045-8b32-dd891611f7cf)
@DonnieBLT sir, it looks like it's already fixed, sir. The image are deleted from the cloud

**Comment by JisanAR03** [comment]
ok sure sir ,, I will test this one by create a new bucket in cloud

**Comment by JisanAR03** [comment]
@DonnieBLT sir, I don't have any cloud ID now , that's why I'm not able to fix this out ,, very sorry sir😔
please let me know sir, if there is any "sandbox or testing account" available.
