### ISSUE TITLE
Task: set up pre-commit

### ISSUE THREAD

**Issue by arkid15r** [OWASP/BLT#1805]
**Is your feature request related to a problem? Please describe.**
At the moment there is no designated control for code style/quality even though README mentions black as a preferred one.

**Describe the solution you'd like**
Introduce pre-commit, make gradual improvements on the code after the initial automated run.

**Additional context**
This will also help improve other code quality aspects if bundled with isort, flake8.

**Comment by Sarthak5598** [comment]
I did notice this issue because when I installed black it showed many commits , why are we not just changing the whole code to black format ?

**Comment by arkid15r** [comment]
> why are we not just changing the whole code to black format ?

This part has already been done. 
I believe after https://github.com/OWASP/BLT/issues/1825 is addressed this issue can be closed.

**Comment by arkid15r** [comment]
Closing this as completed.
