### ISSUE TITLE
Design homepage from mockup 

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#181]
![img_1451](https://cloud.githubusercontent.com/assets/7475382/26772140/bb3bbc10-4991-11e7-8daa-bada61a28440.JPG)

**Comment by souravbadami** [comment]
Hi @seanauriti -- Can you please assign this issue to me ? Because it will prevent multiple people ending up doing the same task.

**Comment by souravbadami** [comment]
Hi @seanauriti -- Could you please reopen this issue ? It is partially fixed.

**Comment by souravbadami** [comment]
Fixed via #549 and previous PR's.
