### ISSUE TITLE
Feature Request: Suggestions for BLT project

### ISSUE THREAD

**Issue by Sarthak5598** [OWASP/BLT#1816]
We can add a suggestion button which redirects us to our discussion board and everyone can write in suggestions for BLT project

**Comment by DonnieBLT** [comment]
We decided against the discussion board because companies may not have a GitHub discussion board, so this will need to be a feature as mentioned in the original description

**Comment by DonnieBLT** [comment]
Oh, this is just a button?

**Comment by DonnieBLT** [comment]
But this is not the original teacher for a discussion board for suggestions

**Comment by Sarthak5598** [comment]
No, Sir this for suggestions related to our project not other companies

**Comment by Sarthak5598** [comment]
Users can add in suggestions related to our project at our discussion board
what do you think?

**Comment by DonnieBLT** [comment]
Yeah, I got it, thats fine. But remember if you are looking for GSOC contributor leaderboard points the code must be on existing issues not new ones that people create for themselves. Otherwise this would be a welcome contribution to the project. Thank you.
