### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by Roboneet** [OWASP/BLT#186]
As the user can't login without email verification(issue #121), the tests don't work now.

**Comment by seanauriti** [comment]
I think it is better to allow the user to not have to verify email, and just show them a banner to verify it when they are on the site like twitter does.

**Comment by farziengineer** [comment]
Which means the user can access the site without verifying email-id. Okay, then reverting the ACCOUNT_EMAIL_VERIFICATION to "OPTIONAL" would do the job.

**Comment by souravbadami** [comment]
@farziengineer -- Indeed!
