### ISSUE TITLE
Restrict comments section to registered members only.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#193]
The current comment section can be accessed by any visitor on the site. It should be restricted to prevent spam and other untraceable activities.

**Comment by seanauriti** [comment]
Also consider using django-comments, I think it has this built in.

**Comment by souravbadami** [comment]
Yes, the current implementation is a very simple model with no combustibility. Comments can neither be edited or deleted.

**Comment by farziengineer** [comment]
Sure those features will be implemented. This was just a start. The only reason I did not use third-party apps, was it might seem like some  magic to new developers and debugging might be hard. 
Thanks

**Comment by seanauriti** [comment]
Thank you.  It is working great.

**Comment by farziengineer** [comment]
Great :+1:
