### ISSUE TITLE
run pipeline actions in paralell?

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1959]
![image](https://github.com/OWASP-BLT/BLT/assets/128622481/c82432b8-7ab7-4332-aada-05bf9e0bb8f7)
I think we can run these in parallel, thougts?

**Comment by AtmegaBuzz** [comment]
Yes it would be much faster, for this parallelism we have to add all the jobs in one file.

alljobs.yml

name:

On:

Jobs:
    job1:
    job2:

Something like this
