### ISSUE TITLE
This button might need some fix

### ISSUE THREAD

**Issue by farziengineer** [OWASP/BLT#196]
This "Change Profile Pic" button on profile page needs to two transition in order to be able to upload pic.
What is mean is that when we click "change profile pic" it takes us from here
![screenshot from 2017-06-06 01 56 43](https://cloud.githubusercontent.com/assets/16963976/26801737/7232faea-4a5b-11e7-984f-5373c44a3d04.png)

to 
![screenshot from 2017-06-06 01 57 29](https://cloud.githubusercontent.com/assets/16963976/26801763/866750a6-4a5b-11e7-9060-ab0084b8b2fe.png), only after this transition the pic can be uploaded. This can be replaced with a single button.

**Comment by seanauriti** [comment]
+1
