### ISSUE TITLE
Still able to post issues without images (this is an important issue to fix as it will reduce spam)

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2017]

**Comment by CodeWithBishal** [comment]
@DonnieBLT 
Removed required from input field
<img width="1440" alt="Screenshot 2024-04-10 at 1 01 25 PM" src="https://github.com/OWASP-BLT/BLT/assets/69814108/cf341ac6-7676-426b-b829-f8d636cfb5d2">


tried to create a new issue, and it asked for a screenshot
<img width="1440" alt="Screenshot 2024-04-10 at 1 01 37 PM" src="https://github.com/OWASP-BLT/BLT/assets/69814108/3a9a3aa2-12a0-48ca-a6b9-55ca7399a399">

can't seem to reproduce this🤔🤔

**Comment by HanilJain** [comment]
@DonnieBLT will it prevent other API from  posting without ss if not I'll work on them.
