### ISSUE TITLE
SSL issue with dev server.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#213]
![screenshot_from_2017-06-06_20-26-36](https://user-images.githubusercontent.com/11073943/26836342-36fe1afc-4af8-11e7-8130-18ca375739b1.png)

/cc @seanauriti @mayank-agarwal-96

**Comment by seanauriti** [comment]
I think you need the latest version of requests.  There was a recent similar issue please check.

**Comment by souravbadami** [comment]
Ah, I remember. Okay, I'll talk to him. He faced the original issue.

**Comment by mayank-agarwal-96** [comment]
I have installed the requirements right before trying to start the server. So I have the latest version of requests.

**Comment by mayank-agarwal-96** [comment]
@seanauriti I have checked the installed requests package and reinstalled the version in requirements.txt too. But the issue persists!

**Comment by seanauriti** [comment]
I added a Django statement to only allow it over https... maybe try disabling that.

**Comment by seanauriti** [comment]
is this still happening?  I would suggest upgrading all modules.  Soon we should also upgrade Django

**Comment by souravbadami** [comment]
Hi @mayank-agarwal-96 -- Could you please update on this ?

**Comment by souravbadami** [comment]
Closing due to lack of response. Also, just FYI -- now we also support setting up the development server on Vagrant. Please follow the wiki for more information on how to do that.
