### ISSUE TITLE
Design the subscribing feature UI.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2334]

**Comment by Uttkarsh-raj** [comment]
These are the designs for the ui for the Sponsor page . The subscription feature has been replaced with the sponsor feature.

<center>
<img width="300" src="https://github.com/OWASP-BLT/BLT/assets/106571927/c56c516f-0fd3-4316-8ddf-e0d13da4d9cb"></img>
<img width="300" src="https://github.com/OWASP-BLT/BLT/assets/106571927/6ad697eb-2dc1-404a-a5a1-e84cd953fef9"></img>
</center>
<br><br>
<img width="300" src="https://github.com/OWASP-BLT/BLT/assets/106571927/0d2bc3de-158d-46b6-a05b-2c1702dcab2c"></img>
