### ISSUE TITLE
Edit comment does not prefill the comment textbox

### ISSUE THREAD

**Issue by jajodiaraghav** [OWASP/BLT#234]
Also, The URL used for comment edit and delete is not clean. We should change it to something more cleaner

**Comment by farziengineer** [comment]
@jajodiaraghav Yes the Edit comment box should prefill. I did not understand what you meant by cleaner URL. Please elaborate.
I will fix it ASAP.
Thank You.

**Comment by farziengineer** [comment]
@jajodiaraghav 
Just saw the Edit and Delete buttons. They look great. 
Thanks for the fix.
