### ISSUE TITLE
GSOC 2024 Leaderboard

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2384]

**Comment by JisanAR03** [comment]
@JisanAR03 

- All PR
    Project-1 : 
        #2254 
    Project-10: 
        #2383 
        
        
 - Close issue
     Project-1 : 
          - #2124
          - #2125 
          - #2126
          - #2127 
          - #2128 
          - #2129 
          - #2130
          - #2131 
          - #2132

**Comment by Sarthak5598** [comment]
@Sarthak5598 

- ALL PR
   Project 1:
       https://github.com/OWASP-BLT/BLT-Lettuce/pull/36
       https://github.com/OWASP-BLT/BLT-Lettuce/pull/39
       https://github.com/OWASP-BLT/BLT-Lettuce/pull/40  
       https://github.com/OWASP-BLT/BLT-Lettuce/pull/46
       https://github.com/OWASP-BLT/BLT-Lettuce/pull/50
       https://github.com/OWASP-BLT/BLT-Lettuce/pull/54  (Redis is on hold due to the server but the code is ready)
       https://github.com/OWASP-BLT/BLT-Lettuce/pull/63
       https://github.com/OWASP-BLT/BLT-Sammich/pull/2
       https://github.com/OWASP-BLT/BLT-Sammich/pull/6
       https://github.com/OWASP-BLT/BLT-Sammich/pull/8
       https://github.com/OWASP-BLT/BLT-Sammich/pull/17

- Project 2: 
       https://github.com/OWASP-BLT/BLT/pull/2366

**Comment by HanilJain** [comment]
@HanilJain 

## Project 1 (Async Notification)

### PR 
1.  #2388 
### Issues solved 
1.  #2213
2.  #2214
3.  #2215
4.  #2216
5.  #2217
6.  #2218
7.  #2221

**Comment by Uttkarsh-raj** [comment]
@Uttkarsh-raj 

- PR's :
  - https://github.com/OWASP-BLT/BLT-Flutter/pull/413
  - https://github.com/OWASP-BLT/BLT-Flutter/pull/412 
  (Will be writing more tests as we build the new features)
  - https://github.com/OWASP-BLT/BLT-Flutter/pull/409
  - https://github.com/OWASP-BLT/BLT-Flutter/pull/406
  - https://github.com/OWASP-BLT/BLT-Flutter/pull/404
  - https://github.com/OWASP-BLT/BLT-Flutter/pull/402
  - https://github.com/OWASP-BLT/BLT-Flutter/pull/401
  - https://github.com/OWASP-BLT/BLT-Flutter/pull/400

- Issue's :
  - https://github.com/OWASP-BLT/BLT-Flutter/issues/408
  - https://github.com/OWASP-BLT/BLT-Flutter/issues/405
  - https://github.com/OWASP-BLT/BLT-Flutter/issues/394
  - https://github.com/OWASP-BLT/BLT/issues/2349
  - https://github.com/OWASP-BLT/BLT/issues/2348
  - https://github.com/OWASP-BLT/BLT/issues/2328
  - https://github.com/OWASP-BLT/BLT/issues/2327
  - https://github.com/OWASP-BLT/BLT/issues/2326
  - https://github.com/OWASP-BLT/BLT/issues/2325
  - https://github.com/OWASP-BLT/BLT/issues/2324
  - https://github.com/OWASP-BLT/BLT/issues/2323
  - https://github.com/OWASP-BLT/BLT/issues/2322
  - https://github.com/OWASP-BLT/BLT/issues/2321
  - https://github.com/OWASP-BLT/BLT/issues/2320
  - https://github.com/OWASP-BLT/BLT/issues/2319
  - https://github.com/OWASP-BLT/BLT/issues/2318
  - https://github.com/OWASP-BLT/BLT/issues/2317
  - https://github.com/OWASP-BLT/BLT/issues/2316
  - https://github.com/OWASP-BLT/BLT/issues/2315
  - https://github.com/OWASP-BLT/BLT/issues/2314
  - https://github.com/OWASP-BLT/BLT/issues/2269
  - https://github.com/OWASP-BLT/BLT/issues/2268
  - https://github.com/OWASP-BLT/BLT/issues/2267
  - https://github.com/OWASP-BLT/BLT/issues/2266
  - https://github.com/OWASP-BLT/BLT/issues/2265
  - https://github.com/OWASP-BLT/BLT/issues/2264
 
- Completed working on : 
  - https://github.com/OWASP-BLT/BLT/issues/2329
  - https://github.com/OWASP-BLT/BLT/issues/2334
  - https://github.com/OWASP-BLT/BLT/issues/2335
  - https://github.com/OWASP-BLT/BLT/issues/2340

**Comment by CodeWithBishal** [comment]
@CodeWithBishal 

- All PRs
   - #2361 
   - #2360 
   - #2354 
   - #2263 
   - #2114 
   - #2102 
   - #2065 
- Issues
- Project 1
   - #2271
   - #2272
   - #2273 
   - #2274 
   - #2275 
   - #2276 
- Project 2: 
   - #2277 
   - #2278 
   - #2279 
   - #2280 
- Project 3: 
   - #2283 
   - #2284

**Comment by thedudeontitan** [comment]
### PRs/Commits:
- https://github.com/OWASP-BLT/BLT/pull/2355
- Hardhat setup and smart contract: https://github.com/OWASP-BLT/BLT-Bounty/commit/2b2338ce3986db7de851cc6b9595a69c70595fdd
- Added Smart Contract Tests: https://github.com/OWASP-BLT/BLT-Bounty/commit/ed305b579d3c2429b403661866609accc6d47d6f
- Hardhat network config: https://github.com/OWASP-BLT/BLT-Bounty/commit/a99db472b601f92639c73a258ac07b874690aa39
- Smart Contract Deployment Script: https://github.com/OWASP-BLT/BLT-Bounty/commit/670840655cd73be32f55a21536d449cbbefd8d68

### Issues Closed:
- https://github.com/OWASP-BLT/BLT/issues/2291
- https://github.com/OWASP-BLT/BLT/issues/2294
- https://github.com/OWASP-BLT/BLT/issues/2295
- https://github.com/OWASP-BLT/BLT/issues/2297
