### ISSUE TITLE
add BLT Tomato to the sidebar

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2386]

**Comment by nikhil25803** [comment]
I want to work on this issue, can you please assign this to me?

**Comment by nikhil25803** [comment]
I am almost done with the changes. I checked, and we are using Font Awesome for fonts in the side navbar. For the BLT tomato, what icon should I use? I checked the website of font awesome [website](https://fontawesome.com/v4/icons/) and didn't find any for it. 

Here's the screenshot of the work so far.
![image](https://github.com/OWASP-BLT/BLT/assets/93156825/e784a1f0-9254-46ca-957d-48023e13f568)

**Comment by nikhil25803** [comment]
I raised a PR for this issue, do look into it once. 
Thanks!
