### ISSUE TITLE
provide better documentation for on-boarding new developers - discuss docker setup and alternative setups

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2759]

**Comment by MrImmortal09** [comment]
@DonnieBLT Can you please assign me this issue

**Comment by MrImmortal09** [comment]
In order to proceed, it's essential that Issue #2793 is resolved and merged first to avoid unnecessary updates to the documentation. Kindly merge the pull request for this issue, or I am happy to resolve it myself if needed.

**Comment by MrImmortal09** [comment]
I've already addressed the issue and submitted a pull request #2801  for it. Please feel free to review and merge it at your convenience.

**Comment by drvcodenta** [comment]
#2967
