### ISSUE TITLE
Add a python linter.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#285]

**Comment by btotharye** [comment]
anything particular you are looking for this or just a linter for travis?

**Comment by seanauriti** [comment]
For Travis is fine

**Comment by btotharye** [comment]
ok if you want to assign to me I'll work on it today after work unless someone else already is working this

**Comment by goyal-sidd** [comment]
@btotharye assigned to you.

**Comment by souravbadami** [comment]
Hi @btotharye -- Any updates on this ?

**Comment by fredfalcon** [comment]
Duplicate of #417
