### ISSUE TITLE
Points are not given when a user submits a bug

### ISSUE THREAD

**Issue by farziengineer** [OWASP/BLT#288]
Hello,
@seanauriti @souravbadami @jajodiaraghav . Is there some change in business logic. As I can see points are not given to the user as soon as they submit the issue. Is this a bug.

Oh, I see, the user uploaded bug is not even seen in the issue page,not even saved in the database .

**Update:** The textarea is not being saved. I'll look into it.
**Update:** The bug is fixed. It was a minor typo, but a major bug. On a serious note, to whoever is changing the UI of the site, please **never** fiddle with the **name** of the html element. because it is the **name** which Django uses to retrieve the data, and save in the database.It can cause unpredictable bugs and open a whole new world of pain.

Thank You.

**Comment by jajodiaraghav** [comment]
Thanks for reporting this @farziengineer 
We should be more cautious while merging so that things like this do not occur again.
