### ISSUE TITLE
Organize views to submodules based on models

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2880]
create submodules within each app:

myapp/
├── views/
│   ├── product.py
│   ├── order.py
│   ├── user.py
│   └── __init__.py
└── models.py

	•	Each file in the views folder could correspond to different models

**Comment by 1010varun** [comment]
@DonnieBLT can you please assign this issue to me.

**Comment by 1010varun** [comment]
@DonnieBLT can you kindly review this
