### ISSUE TITLE
Create badges for users that can be earned automatically or given from a mentor

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2885]
Have a badge for mentor
Have a badge for copilot user 
Have a badge for openai
Have a badge for a GSOC student 
Have badges be nicely designed

**Comment by 1010varun** [comment]
@apoorvapendse are you still working on this or can I work on it?

**Comment by 1010varun** [comment]
@DonnieBLT just need a little more context on this

**Comment by 1010varun** [comment]
@tsu-ki I'm interested in this issue, but if you're keen on working on it and prefer not to check whether I'm working on it, feel free to proceed.

**Comment by tsu-ki** [comment]
@1010varun oh, I did not know you've already started to work on this. I was working on the recommendations feature where i had to add a badge for it, and this issue seemed similar to it, so I assigned it to myself.
If you're currently working on it, please let me know, I'll unassign myself

**Comment by 1010varun** [comment]
No worries bro go ahead

**Comment by tsu-ki** [comment]
i'm still working on this one and it should be done in a day or two.

**Comment by tsu-ki** [comment]
@DonnieBLT can you please explain, how should I add the ability for an user to automatically earn the badge?

**Comment by tsu-ki** [comment]
i'm not sure how I got unassigned but just to be sure, I'm working on this issue currently and have asked for further explanation to implement the earn badges automatically feature

**Comment by tsu-ki** [comment]
@krrish-sehgal hey! i’m currently working on this issue and have been struck by an error, I was waiting for an explanation for the same but have started to solve it on my own. Can you please unassign yourself?

**Comment by tsu-ki** [comment]
> Sure feel free to commit the pull request if we need to separate to a separate issue we can

Sure, I'll create a PR for the same after reaching back home
