### ISSUE TITLE
Use case of number of views on the issue page .

### ISSUE THREAD

**Issue by farziengineer** [OWASP/BLT#290]
Hello, it might be a noob question but what is the use of the view count (here it is 26).
![screenshot from 2017-06-13 16 08 20](https://user-images.githubusercontent.com/16963976/27078746-8fcdef40-5052-11e7-9374-dd6459ceef39.png)

It increments by one every time a user (authenticated or not) access it.  I think it should have some restrictions. Any thoughts? @seanauriti @jajodiaraghav @souravbadami .

**Comment by jajodiaraghav** [comment]
Hi @farziengineer This is a perfectly valid question. Something similar popped in my mind a few days ago.

Though the view count serves a purpose of showing how many people viewed the page, it still increments in a pretty unrestricted fashion.
But storing name/id of every person who viewed the page can be a problem if 1000s of people use the app. Also, we cannot do anything about the people who aren't authenticated. 

It is a point of discussion!

**Comment by farziengineer** [comment]
"storing name/id of every person who viewed the page can be a problem if 1000s of people use the app". 
Agreed.

**Comment by farziengineer** [comment]
Okay so, I searched and found out that it can be done using cookies. Sure the user may delete or block the cookies, but it is a bit more accurate.

**Comment by souravbadami** [comment]
I'd like to drop in and add my few cents to it. Why do you guys think that maintaining an entity for views is not possible or is a burden ? How about a new model, **IssueViews** -- which keeps tracking a users view for an issue (or maybe a single view when there's a hit by an authenticated user). It is not going to cost too much. Yes, it is not going to be a good idea if there's no rock solid use case of the functionality. So, I'd say -- the main discussion here is the use case for such a feature.

**Comment by farziengineer** [comment]
@souravbadami @jajodiaraghav . That doesn't even require a new model, it can be done using ManyToManyFields, but again, the question in the context is efficiency and use cases.Let's wait for @seanauriti 's views.

**Comment by souravbadami** [comment]
@farziengineer -- Yes, we can absolutely do that and that would be the simplest way to achieve this feature. But if we use a new model, we can take in several other relation between a user and an issue and keep things cleaner.

**Comment by seanauriti** [comment]
My thoughts are:

1) the view counter serves as a general gauge of the importance of the bug by the community.  If it got reported at 10am and has 120 views by 11am you can expect it is getting attention.

2) we are on a limited free database of 10,000 rows.  I would prefer those are filled with bugs and users before we have to pay to upgrade.

3) if we can implement a free solution that would be good.  

Otherwise we can discuss this in 3 months or so when we have more resources.
