### ISSUE TITLE
Update the GSOC page with more info and make it look nicer

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2911]

**Comment by tsu-ki** [comment]
@DonnieBLT Could you please explain, what changes should be made to GSOC page?

**Comment by tsu-ki** [comment]
@DonnieBLT BLT has been attending GSOC consecutively from 2020 till 2024? Also, which leaderboard should be linked to the page? 
Thank you for giving so many insights on the issue.

**Comment by krrish-sehgal** [comment]
@tsu-ki seems like you've taken over this issue, since i haven't done much work on this yet... I'll unassign me.

**Comment by tsu-ki** [comment]
@DonnieBLT can you please close this issue? I'm not able to assign myself another issue.

**Comment by tsu-ki** [comment]
@apoorvapendse thank you for informing me that, I forgot to add the PR number this time, I'll keep this in mind
