### ISSUE TITLE
update the views image to show a chart and use the IP table for the data

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2920]
![Image](https://github.com/user-attachments/assets/d7527b6f-30dc-44e0-a3d7-474547c9fc9c)

**Comment by tsu-ki** [comment]
@apoorvapendse just a request, can I take over this issue if you're not working on it at the moment? I didn't realise that you were already assigned to this and I went ahead to work on this issue, I believe I've done with almost everything. thank you!
