### ISSUE TITLE
Description box size.

### ISSUE THREAD

**Issue by farziengineer** [OWASP/BLT#293]
Hello everyone, @seanauriti @jajodiaraghav @Roboneet @souravbadami 
1.I was wondering that shouldn't the **Description box** be a bit bigger. It looks a bit cramped between website link and the dropdown menu. Since it is a **description box**, it should be a bit a bit large.
2.Secondly, can we have a lower bound on the number of characters, a user has to input in the description box, so that the bug is a bit more descriptive. Looking forward to everyone's views.
![screenshot from 2017-06-15 22 20 05](https://user-images.githubusercontent.com/16963976/27192621-ba12f8cc-5219-11e7-85ee-6fcd7ab78ee1.png)

**Comment by jajodiaraghav** [comment]
Well @farziengineer, I am sure there is an open issue that talks about the redesigning the issue form.
What I was thinking is to remove the form from the header and put it in a separate template which can be included in the required pages.

> Can we have a lower bound on the number of characters

Although the field is required, I don't think putting a lower bound would help as sometimes the screenshot for the issue becomes self explanatory. In that case, the user can just type "Refer image". What do you think?

**Comment by farziengineer** [comment]
> put it in a separate template which can be included in the required pages.

I think it is already done. See **base.html**. 
For the second, part yeah I think it might suffice to type "Refer image" . Let's hear what other have to say.

**Comment by souravbadami** [comment]
If there's a viewing issue with the description box, then I'd suggest dragging it downwards -- as it is expandable vertically. But, if you could suggest something better by keeping it at it current location -- that would be great as it's cleaner that way.

For the lower bound suggestion, I'd stick with the current implementation. @jajodiaraghav's explanation is pretty satisfactory to keep it as it is.

**Comment by jajodiaraghav** [comment]
Should we close this? We already have a new /report page
