### ISSUE TITLE
Email for verification always ends up in spam and contains long verification link.

### ISSUE THREAD

**Issue by apoorvapendse** [OWASP/BLT#2934]
Tried creating an account with two different accounts, ends up in spam
![Image](https://github.com/user-attachments/assets/73a0c19c-f5e0-440e-ba97-a54c967d6df3)

  
A suggestion would be to add an href tag instead of copying that long string containing the token  
and pasting it in the browser. 
This would be better from a UX standpoint imo.

**Comment by 1010varun** [comment]
@apoorvapendse can you please review and merge this? If any changes are required then let me know.
