### ISSUE TITLE
Annoying toast that blocks access to the authentication button after signing out.

### ISSUE THREAD

**Issue by apoorvapendse** [OWASP/BLT#2935]
Whenever I want to logout and login to some different account, the signup toast doesn’t let me do that, and if I hover on it, it ends up staying as it is in its position, blocking me from clicking the login button.

Clicking on the toast makes it disappear, hovering doesn't

Here is the video that captures this behavior.
https://drive.google.com/file/d/1TZn4MDHmNsTwz-TxYrABAiKJsrocpaUJ/view?usp=sharing

**Comment by tsu-ki** [comment]
I'm working on this one right now. I apologise for not being able to assign myself the issue.

**Comment by tsu-ki** [comment]
@apoorvapendse can you please point towards the location of the codeblock for this toast? I searched through the directly multiple times but couldn't find anything.

**Comment by 1010varun** [comment]
@tsu-ki I think you are already working on a issue if you are not working on this one can I assign this to myself?
