### ISSUE TITLE
Post new content to blue sky

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2955]

**Comment by krrish-sehgal** [comment]
@DonnieBLT sir, could you provide any description about what needs to be done here?
Thanks

**Comment by harsh3dev** [comment]
@DonnieBLT Please could you elaborate on what the issue is?

**Comment by krrish-sehgal** [comment]
The PR for the activity stream #2931 is raised by me, is it one you are talking about ?

**Comment by krrish-sehgal** [comment]
Okay, could you see if any more changes are needed? i resolved all the conversations in my last commit.
Thanks.

**Comment by krrish-sehgal** [comment]
Proposed Solutions for Posting to BlueSky: 

----Moderator-Driven Approval System:-----

1.Create a database table (e.g., moderators) to manage restricted users who can approve content for BlueSky.
2.Only moderators will see the "Approve for BlueSky" button in the activity feed.
3.Once approved, the content will be marked with an isApprovedForBlueSky flag and visually highlighted (e.g., a blue label).
4.A backend process will automatically post content with this flag to BlueSky using the API. This ensures controlled, manual moderation.

----Automatic Approval Based on Thresholds:----

1.Implement a threshold system where content gets automatically approved if it meets specific conditions, e.g., likes ≥ 10 and dislikes ≤3 
2.Once content reaches the threshold, it is flagged with isApprovedForBlueSky and posted to BlueSky via the API.
3.This reduces manual effort, but moderators can still intervene manually for exceptional cases to add the flag.
