### ISSUE TITLE
username and email is lost when there is a signup error, it should stay

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2956]
![Image](https://github.com/user-attachments/assets/43d21ab9-3fa9-4f33-86cf-a148b5b12d7d)

**Comment by tsu-ki** [comment]
@SahilDhillon21 hey, I'm sorry for not informing you beforehand but I've already raised a PR for this issue. I did not assign it to me because the bot's not letting me assign issues as my merged PRs aren't closed
