### ISSUE TITLE
some images are not loading while other are

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2971]
for example, some recent images on the issues list are not loading and also some of the user avatar images are not loading

**Comment by tsu-ki** [comment]
i'll be working on this one

**Comment by krrish-sehgal** [comment]
@DonnieBLT and @tsu-ki  i have some analysis from when i got stuck on this issue.


The error in the backend , which is "
django.db.utils.OperationalError: database is locked
[15/Nov/2024 03:03:04] "GET /media/screenshots/home.pngca2ea533-6329-48ad-b3fb-54bffa17.png HTTP/1.1" 500 159625
[15/Nov/2024 03:03:04,186] - Broken pipe from ('127.0.0.1', 54388)"

there's a race condition or deadlock being produced between 2 queries trying to read/write the database.
More specifically there can be 2 possible things happening here ,

First(highly likely)
When i tried to log all the queries executing on the db i found that just before the "image get" request there are some queries running

before error is produced:
"DEBUG:django.db.backends:(0.000) SELECT "website_ip"."id", "website_ip"."address", "website_ip"."user", "website_ip"."issuenumber", "website_ip"."created", "website_ip"."agent", "website_ip"."count", "website_ip"."path", "website_ip"."method", "website_ip"."referer" FROM "website_ip" WHERE "website_ip"."id" = 1 LIMIT 21; args=(1,); alias=default
(0.000) SELECT "website_ip"."id", "website_ip"."address", "website_ip"."user", "website_ip"."issuenumber", "website_ip"."created", "website_ip"."agent", "website_ip"."count", "website_ip"."path", "website_ip"."method", "website_ip"."referer" FROM "website_ip" WHERE "website_ip"."id" = 1 LIMIT 21; args=(1,); alias=default
(0.000) SELECT "website_ip"."id", "website_ip"."address", "website_ip"."user", "website_ip"."issuenumber", "website_ip"."created", "website_ip"."agent", "website_ip"."count", "website_ip"."path", "website_ip"."method", "website_ip"."referer" FROM "website_ip" WHERE "website_ip"."id" = 1 LIMIT 21; args=(1,); alias=default

DEBUG:django.db.backends:(0.000) SELECT "website_ip"."id", "website_ip"."address", "website_ip"."user", "website_ip"."issuenumber", "website_ip"."created", "website_ip"."agent", "website_ip"."count", "website_ip"."path", "website_ip"."method", "website_ip"."referer" FROM "website_ip" WHERE "website_ip"."id" = 1 LIMIT 21; args=(1,); alias=default

Internal Server Error: /media/screenshots/bruger.jpe8fc54280-dde8-4da8-a116-b1436c.jpeg
Traceback (most recent call last):"

so maybe the race condition is between these two but i am unable to locate where the query is getting triggered from.

Second (Less likely)
in _bug.html when we call this
"img class="bug-img h-[100%] w-[200px] object-contain"
src="{{ bug_screenshots.0.image.url }}"
alt="bug screenshot"
width="200px"
height="100%"
{% else %}"

here image.url tries to access the database several times, but i checked with one at a time as well... the image was randomly rendering and sometimes not.

**Comment by tsu-ki** [comment]
@krrish-sehgal I did not know that was happening, thank you. Since, I haven't done much work on this one yet, would you like to take it over? It seems you can resolve it more efficiently.

**Comment by krrish-sehgal** [comment]
I was stuck on it for a long time, maybe this problem needs a different perspective.

**Comment by tsu-ki** [comment]
@DonnieBLT Can you please elaborate on the problem and what @krrish-sehgal said about it? It would be really helpful
