### ISSUE TITLE
users are being duplicated on the leaderboard

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#2974]
![Image](https://github.com/user-attachments/assets/31ed982d-50bb-4a3a-9694-f1596d601820)

**Comment by krrish-sehgal** [comment]
sir which url is this , as i am not facing this issue on (base_url)/leaderboard/

**Comment by tsu-ki** [comment]
@krrish-sehgal is it okay if I tackle this one? I tried locating the deadlock problem in the other issue but couldn't(https://github.com/OWASP-BLT/BLT/issues/2971)

**Comment by krrish-sehgal** [comment]
are you able to see the duplicates though?

**Comment by tsu-ki** [comment]
@krrish-sehgal the problem could be found in the leaderboard_widget file present in templates folder.  
I tackled it by creating a unique filter which runs a loop for each unique username and only allows it to get displayed once.  
I’m travelling right now so cannot make a PR but will do so, once i’m back home.

**Comment by krrish-sehgal** [comment]
Sure , this is all yours :)

**Comment by tsu-ki** [comment]
@apoorvapendse Could you please ask before taking over an issue? I mean, you could have suggested the more efficient solution rather than just taking it over and disregarding my efforts.

**Comment by tsu-ki** [comment]
@apoorvapendse oh, come on. I clearly stated that I was gonna make a PR once I got back home. I couldn't assign myself the issue which is why I asked krrish if it's okay for me to resolve this one.
