### ISSUE TITLE
Incorrect styling  of the links and the alignment of the text

### ISSUE THREAD

**Issue by Shashwat-srivastav** [OWASP/BLT#2985]
![Image](https://github.com/user-attachments/assets/1c5a5701-6b5d-47b6-81b7-33e1c66b1c1c)

**Comment by tsu-ki** [comment]
I was going to report this issue before, thank you

**Comment by kartik-212004** [comment]
i would like to solve this issue

**Comment by tsu-ki** [comment]
@kartik-212004 I've already made a PR for this issue which now needs to be reviewed and merged. I would suggest you solve another open issue :)

**Comment by kartik-212004** [comment]
Okay thanks
