### ISSUE TITLE
Comments rendered does not build upwards

### ISSUE THREAD

**Issue by farziengineer** [OWASP/BLT#305]
The comments are rendered in issue.html grows downwards, i.e. If a comment C2 is posted after C1, 
C2 is rendered below C1. Instead we should have C2 rendered above C1.
![screenshot from 2017-07-08 11 12 09](https://user-images.githubusercontent.com/16963976/27982930-544afe1a-63ce-11e7-8bcd-bf764731239b.png)

The second comment should be above the first comment

**Comment by farziengineer** [comment]
z

**Comment by goyal-sidd** [comment]
Why is it wrong with it being this way though? The comments here are on a particular issue.

**Comment by farziengineer** [comment]
Think about it and look for examples, when I add a comment if the comment
does not appear on top and there are large number of comment s already
there, l will have to scroll down to see if my comment was actually
posted.The aim is to see the comment posted as near as possible. If I'm not
clear please ping.

**Comment by farziengineer** [comment]
Example: see at hackerearth

**Comment by seanauriti** [comment]
I think comments should be like Github, where the last one last one is the latest and the comment area is on the bottom.  Also it's similar to Gmail.

**Comment by farziengineer** [comment]
Fixed in #305
