### ISSUE TITLE
Footer for the website.

### ISSUE THREAD

**Issue by goyal-sidd** [OWASP/BLT#306]

**Comment by jajodiaraghav** [comment]
There already is a footer on the index page. I would love to see a new design of the footer. We can also include it in other pages then. What do you think?

**Comment by goyal-sidd** [comment]
Mostly I am thinking along the lines of a more cleaner look. Like instead of links to social network follows, we can have icons etc. 
Any particular suggestions if anyone has will be most welcome.

**Comment by goyal-sidd** [comment]
@jajodiaraghav you said about including new pages. Could you give me a rough idea for it. 
Till now I have made this. If there are new links to be added then it would be great, I can categorise them much better for a better interface.
![footer](https://user-images.githubusercontent.com/17125030/27994330-4bac395c-64d9-11e7-81e8-8b7d3f18a080.png)

**Comment by jajodiaraghav** [comment]
@goyal-sidd The design looks so cleaner. Good work!

You do not have to include it in new pages. All you have to do is replace this codeblock here: https://github.com/OWASP/BLT/blob/master/website/templates/base.html#L210-L222 with your code.
Also paste the css part in styles.css file.

Feel free to ask questions is you have. :)

**Comment by goyal-sidd** [comment]
Thanks! I made a new page while testing, it is easier to start from fresh. I will paste in only.
Are there any other links that we would want? If there are it would be better if I add them right now, so I can put them in proper categories.

**Comment by jajodiaraghav** [comment]
We do not have any other links to add right now. But we might have to add later.
Please create a PR
