### ISSUE TITLE
add end time to sizzle report for a user

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#3091]

**Comment by tsu-ki** [comment]
@DonnieBLT Sir can you please help me understand how can I implement this functionality? I haven't resolved any issue related to Sizzle earlier so having a little difficulty understanding the problem

**Comment by tsu-ki** [comment]
@DonnieBLT Should I still work on the issue? As it seems the same error was solved and merged in a previous PR.
Please do guide me further on this one, thank you!

**Comment by tsu-ki** [comment]
/unassign 
Unassigning myself after my conversation with @JisanAR03 over Slack. Please do tag me if the issue needs to be worked on even after your discussion with @DonnieBLT sir
