### ISSUE TITLE
Images are not appearing on the GitHub issue that are reported from the website

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#3152]

**Comment by tsu-ki** [comment]
<img width="1398" alt="Image" src="https://github.com/user-attachments/assets/3a046bd4-aa56-4a82-ae30-0e23b0937c1b" />

@DonnieBLT Sir the images are appearing when accessing the website using desktop

**Comment by tsu-ki** [comment]
Thank you, understood.
