### ISSUE TITLE
Make a new page for creating issues.

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#336]
Make sure it works with the chrome extension.
Also have an automated test to make sure it works.

**Comment by souravbadami** [comment]
Hi @seanauriti -- In this case, are we keeping the current issue creation panel on the top header ?

**Comment by seanauriti** [comment]
Let's think about it.  I think I may want the homepage to be a nice bug reporting page, instead of a separate page.  We do want to encourage people to enter bugs, so if it's on the homepage it may be better.

**Comment by goyal-sidd** [comment]
A new page can help people, it will look more organised and we can give a short description of every field there, if user is unable to decipher any field.

The report a bug can be made as a prominent button.

**Comment by souravbadami** [comment]
@seanauriti -- So, for now I'm integrating a new issues page and also keeping the issues form on the home header intact. It will not be visible on other pages and can be accessed via the new issue reporting form. What do you think ?

**Comment by seanauriti** [comment]
Sounds good

**Comment by jajodiaraghav** [comment]
@seanauriti  Should we close this?

**Comment by souravbadami** [comment]
I think so. Fixed via #338.
