### ISSUE TITLE
Autocomplete in comments section

### ISSUE THREAD

**Issue by farziengineer** [OWASP/BLT#341]

**Comment by jajodiaraghav** [comment]
Are you planning to use typeahead.js for this. Instead of autocomplete, we could create "user-mentions" feature just like in github.

**Comment by farziengineer** [comment]
Thanks for suggestion, I go with typeahead.

**Comment by farziengineer** [comment]
By user mentions do you mean this @jajodiaraghav . Then yes, by autocomplete I meant the same.
