### ISSUE TITLE
Social share icon alignment issue.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#565]
![screen shot 2017-09-15 at 6 48 05 pm](https://user-images.githubusercontent.com/11073943/30483990-8702abba-9a46-11e7-8c51-f550a158a46f.png)

**Comment by Nicorules** [comment]
May I be assigned to solve this issue?

**Comment by seanauriti** [comment]
Yes

**Comment by Nicorules** [comment]
Thanks!

**Comment by seanauriti** [comment]
I created a tag for you - https://github.com/OWASP/BLT/labels/Asignee%3A%20Nicorules

**Comment by Nicorules** [comment]
Thanks! I am working on it.

David.

Sent from Mail for Windows 10

**Comment by souravbadami** [comment]
Fixed via #594.
