### ISSUE TITLE
Improve page views logic.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#576]
Currently page views can be increased drastically without any intervention from our system. Here's an example issue for which a simple page request bot did the same.

Issue: https://www.bugheist.com/issue/733/

![screen shot 2018-02-20 at 7 24 11 pm](https://user-images.githubusercontent.com/11073943/36427598-acba3900-1673-11e8-8cde-f494f8650173.png)

**Comment by srahulbadami** [comment]
I want to work on this issue .

**Comment by souravbadami** [comment]
@srahulbadami -- Assigned!

**Comment by souravbadami** [comment]
Fixed via #602.
