### ISSUE TITLE
AssertionError: Header values must be strings

### ISSUE THREAD

**Issue by srahulbadami** [OWASP/BLT#590]
After Setting Up Development Server using Virtual Environment , got the following error : 

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
>     self.result = application(self.environ, self.start_response)
>   File "/home/rahulbadami/BLT/venv2/local/lib/python2.7/site-packages/whitenoise/base.py", line 121, in __call__
>     return self.serve(static_file, environ, start_response)
>   File "/home/rahulbadami/BLT/venv2/local/lib/python2.7/site-packages/whitenoise/base.py", line 132, in serve
>     start_response('200 OK', headers.items())
>   File "/usr/lib/python2.7/wsgiref/handlers.py", line 180, in start_response
>     assert type(val) is StringType,"Header values must be strings"
> AssertionError: Header values must be strings

![preview](https://user-images.githubusercontent.com/22706287/36944417-b69546b6-1fc1-11e8-8c13-761f4e7137fc.png)

**Comment by seanauriti** [comment]
may be related to - https://github.com/kennethreitz/dj-static/issues/25

maybe try upgrading whitenoise or other packages...

**Comment by souravbadami** [comment]
Fixed via #591.
