### ISSUE TITLE
Footer Alignment Issue in Issue Page 

### ISSUE THREAD

**Issue by srahulbadami** [OWASP/BLT#592]
![screenshot from 2018-03-04 21-45-35](https://user-images.githubusercontent.com/22706287/36947836-637564a8-1ff7-11e8-8010-bde8ae1fae68.png)

**Comment by souravbadami** [comment]
@srahulbadami -- Would you like to work on this ?

**Comment by srahulbadami** [comment]
yes, I would like to work on this issue.

**Comment by seanauriti** [comment]
We also have a new design coming.
