### ISSUE TITLE
check domain name resolves to IP address before posting

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#619]
This will prevent entries that do not match up with domains.

- [ ] do not perform a dns lookup if the bug report is a server error or downtime.

**Comment by souravbadami** [comment]
@fredfalcon -- You mean to investigate domain existence and resolution to a server before posting ?

**Comment by fredfalcon** [comment]
Yes, so someone can’t post kgdkdykgd.com we might as well check the full
page exists too unless it was a 404 or similar error

**Comment by souravbadami** [comment]
Yeah! That's a good idea.

**Comment by fredfalcon** [comment]
- [ ] do not perform a dns lookup if the bug report is a server error or downtime.
