### ISSUE TITLE
Typo in HUD Tutorial

### ISSUE THREAD

**Issue by victorsalmon** [OWASP/BLT#673]
In the HUD Tutorial, on the "Alert Notifications" screen, it says:

'The first time that ZAP find a specific type of issue with a site it will show the name of the issue in a notification that appears in the bottom right hand corner of your browser'.

I believe it should read 'that ZAP find**s**'.

Thank-you for all your awesome, hard work! ^.^
-Victor

**Comment by fredfalcon** [comment]
Not seeing this.  Maybe it was deleted.
