### ISSUE TITLE
For anonymous issue reporting, add a captcha to prevent spam - please use django-captcha

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#681]

**Comment by ankit2001** [comment]
I will modify it ASAP @fredfalcon .

**Comment by Sparsh1212** [comment]
Can I work on this? Also, please tell do I have to use this pip package for implementing this:
https://django-simple-captcha.readthedocs.io/en/latest/usage.html

**Comment by fredfalcon** [comment]
That would be great.  Thanks @Sparsh1212

**Comment by ankit2001** [comment]
I was working on it @Sparsh1212 .

**Comment by fredfalcon** [comment]
Can we have a time limit.  If the issue is not done in 5 days or so it gets unassigned?  You guys can work out who will take this issue.

**Comment by Sparsh1212** [comment]
@ankit2001 If that's the case, you can take this. No problem.

**Comment by ankit2001** [comment]
Thanks @Sparsh1212 .

**Comment by fredfalcon** [comment]
How is it going?

**Comment by ankit2001** [comment]
Ohh i will do it today i was doing internationization and swagger APIs stuff before, also adding some unit tests. Will complete it today.
