### ISSUE TITLE
Hide Liked By Button for issues having 0 likes

### ISSUE THREAD

**Issue by Sparsh1212** [OWASP/BLT#699]
For the issues which have 0 likes, we can hide the "Liked By" button. The current UI which shows the empty list for 0 likes looks inappropriate. It will be better to hide the button.

![image](https://user-images.githubusercontent.com/55937724/112892281-bfd9ab00-90f6-11eb-8da2-e504d1508d5a.png)

**Comment by Sparsh1212** [comment]
@fredfalcon What do you think? If this seems right, then I would love to fix this.

**Comment by fredfalcon** [comment]
that is fine
