### ISSUE TITLE
A dependent bot flow + github actions is required to automate the prs in repo

### ISSUE THREAD

**Issue by ankit2001** [OWASP/BLT#700]
@fredfalcon i think we should add dependent bot workflow + gch actions to the repository to automate the PRs.

**Comment by fredfalcon** [comment]
@ankit2001 thanks for the PR about the dependabot - I have merged it.  What other actions did you want to enable?  Can you please link them?

**Comment by ankit2001** [comment]
Yes, i want to enable testing actions for automation of pr, and also codeql for code analyses.

**Comment by fredfalcon** [comment]
We have Travis, check the readme

**Comment by ankit2001** [comment]
Okay then i will add codeql for code ananysis, and can we add pr template for the repo for new contributor, also can we shift thr prs from master to dev?

**Comment by ankit2001** [comment]
@fredfalcon As we are using master branch for the prs, can we just shift to prs against dev branch?

**Comment by fredfalcon** [comment]
I think direct to main / master is faster.  Let’s keep concise feature branches and possible setup review apps

**Comment by ankit2001** [comment]
Thans @fredfalcon  for the suggestions.

**Comment by fredfalcon** [comment]
Any other ones?
