### ISSUE TITLE
Add Documentation for REST Api's

### ISSUE THREAD

**Issue by spiderxm** [OWASP/BLT#717]

**Comment by ankit2001** [comment]
@fredfalcon , i am intereseted in this, plzz assign this to me.

**Comment by fredfalcon** [comment]
Please use this https://django-rest-swagger.readthedocs.io/en/latest/

**Comment by fredfalcon** [comment]
You can add closes or fixes in the commit message to auto close the issue on merge

**Comment by ankit2001** [comment]
Thanks @fredfalcon .
