### ISSUE TITLE
Add django-rest-auth signup so we can signup from the app

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#726]
https://django-rest-auth.readthedocs.io/en/latest/installation.html

**Comment by ankit2001** [comment]
I am interested in this @fredfalcon . Please assign me this.

**Comment by fredfalcon** [comment]
try the new issue assigner

**Comment by ankit2001** [comment]
Assign to me

**Comment by ankit2001** [comment]
assign to me

**Comment by ankit2001** [comment]
@fredfalcon , how can we use it?

**Comment by ankit2001** [comment]
Ohh, it worked on lower case assign to me, thanks @fredfalcon
