### ISSUE TITLE
Email Verification is not working properly for the registration

### ISSUE THREAD

**Issue by ankit2001** [OWASP/BLT#781]
Current code is not able to send emails and verify a user while calling the Rest API for registration.

**Comment by fredfalcon** [comment]
@ankit2001 can you explain a bit more?

**Comment by ankit2001** [comment]
@fredfalcon Current Backend API for APP does not support Email Verification.
A error is occuring while verification. We need to fix that on Backend. Or the error is might be on main server not on staging server due to credentials issues.

**Comment by fredfalcon** [comment]
@ankit2001 it looks like the url is calling `/api/v1/auth/registration/` but that url can't be found.

**Comment by fredfalcon** [comment]
The URL was wrong, I updated it and now it's sending an email
