### ISSUE TITLE
Signin With Github, Google, Facebook not Working

### ISSUE THREAD

**Issue by AtmegaBuzz** [OWASP/BLT#922]
Steps to Reproduce:
1. go to https://bugheist.com
2. try to login using third party. 
3. redirects to local host instead of bughiest

**Comment by AtmegaBuzz** [comment]
In the production the .env has CALLBACK_URL_FOR_GOOGLE=localhost so to fix it we have to change it in production env @fredfalcon 
![image](https://user-images.githubusercontent.com/68425016/202858712-b08314a3-699a-4201-82b2-18dd56e9e0cf.png)

**Comment by fredfalcon** [comment]
What are the callbacks?

**Comment by fredfalcon** [comment]
Just the base url?

**Comment by AtmegaBuzz** [comment]
i think we have to add CALLBACK_URL_FOR_... in out environment of the prod server
