### ISSUE TITLE
Revert main leaderboard to how it was before

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#938]

**Comment by AtmegaBuzz** [comment]
@fredfalcon why

**Comment by fredfalcon** [comment]
It’s supposed to list everyone - it seems like it changed.  We did not require any changes to the global leaderboard.  Attached is the global leaderboard from the app which is correct.
![BC6AD8DE-3DEB-4438-AE2D-2446AB715E90](https://user-images.githubusercontent.com/7475382/187034787-b55c417a-3808-4612-ba4a-9762bd23b443.png)

**Comment by AtmegaBuzz** [comment]
@fredfalcon 
![image](https://user-images.githubusercontent.com/68425016/187036352-60fd8adb-d4eb-47eb-ade5-5a10d8d3745b.png)

**Comment by fredfalcon** [comment]
Thank you!
